### PR TITLE
Update protect-mam-windows.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the windows version in the note to 19045

Fixes https://github.com/MicrosoftDocs/memdocs/issues/4427

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Erikre Please review and sign off this PR. Thanks

**Review by Erikre — APPROVED** [review]

**Comment by Erikre** [comment]
Verifying with PM.

**Comment by Erikre** [comment]
#sign-off

**Pull request merged**
