### PR TITLE
Update security-baselines-monitor.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the navigation

fixes#https://github.com/MicrosoftDocs/memdocs/issues/3528

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by yogkumgit** [comment]
@Brenduns Please signoff this PR. Thank

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by Brenduns** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
