### PR TITLE
Update cloud-pc-size-recommendations.md

### PR DESCRIPTION
**Pull request by christiaanbrinkhoff**
Added Nested Virt

### CODE REVIEW

**Comment by PRMerger5** [comment]
@christiaanbrinkhoff : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger5** [comment]
@christiaanbrinkhoff : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ErikjeMS** [comment]
#sign-off

**Comment by jborsecnik** [comment]
@ErikjeMS, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by jborsecnik** [comment]
assign #christiaanbrinkhoff

**Comment by ErikjeMS** [comment]
This is an old PR that's now out of date and in conflict, so closing. @christiaanbrinkhoff, if changes still must be made, please open a PR on the private repo.

**Pull request closed without merging**
