### PR TITLE
Update autopilot-faq.yml

### PR DESCRIPTION
**Pull request by JuanitaBaptiste**
removed support line item for Autopilot on IoT

### CODE REVIEW

**Comment by PRMerger14** [comment]
@JuanitaBaptiste : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by JuanitaBaptiste** [comment]
#sign-off

**Comment by PRMerger-2** [comment]
@JuanitaBaptiste: I'm sorry - only the author of this article, @greg-lindsay, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by aczechowski** [comment]
Reopening for @JuanitaBaptiste, and signing off on behalf of author who is currently out.
#label:"ready-to-merge"

**Pull request merged**
