### PR TITLE
Page Improvement: Microsoft Intune MDM Lifecycle

### PR DESCRIPTION
**Pull request by allusai**
Hello! I would like to suggest an improvement to the "MDM Lifecycle" page. When I first read this page, I saw that the first paragraph did a good job of explaining how Intune helps you at different points of the device lifecycle. But I wanted to make it more clear to first-time users and maybe non-technical users how this concept is relevant to them in terms of using Intune for their company. That's why I added an example of the different points of an iPad's device lifecycle to clarify to readers how Intune helps you manage that iPad from when you first start using it to when you need to decommission it.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@allusai : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Admin note: If the PR is approved, remove the locale from the docs.microsoft.com URL before merging. The PR review team can do this.

**Comment by ErikjeMS** [comment]
@allusai Thanks! You'll just need to fix the URL as explained above.
#sign-off

**Comment by ktoliver** [comment]
I removed the locale from the microsoft.com URL and made some punctuation and grammar edits. We'll merge the PR now. Thanks!

**Comment by allusai** [comment]
Thank you so much for accepting the change!

**Pull request merged**
