### PR TITLE
Update licenses.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated license options as intune in available in A3 and A5

### CODE REVIEW

**Comment by PRMerger9** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Erikre Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@Erikre Gentle reminder

**Comment by Erikre** [comment]
No A5 license exists that I'm aware of or that I could find in any Microsoft domain. Closing.

**Review by Erikre — APPROVED** [review]

**Comment by Erikre** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
