### PR TITLE
Update user-experience-analytics-preview.md

### PR DESCRIPTION
**Pull request by zdvorak**
Added FAQ about AccountMove scenario per Task: 6177827

### CODE REVIEW

**Comment by PRMerger17** [comment]
@zdvorak : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
#sign-off on behalf of @mestew who is out of the office (or will prmerger bark at me in the public repo?)

**Comment by PRMerger9** [comment]
@aczechowski: I'm sorry - only the author of this article, @mestew, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by aczechowski** [comment]
Emailed review team for exception

**Comment by PRMerger10** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
