### PR TITLE
Update organizational-messages-prerequisites.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated licensing requirements

fixes#https://github.com/MicrosoftDocs/memdocs/issues/3476

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by traya1** [comment]
Learn Build status updates of commit _[680fb08](https://github.com/msbemba/memdocs/commits/680fb0812134bd3be40368bebfc8f963aa8c5173)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[memdocs/intune/remote-actions/organizational-messages-prerequisites.md](https://github.com/msbemba/memdocs/blob/patch-186/memdocs/intune/remote-actions/organizational-messages-prerequisites.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/aa268e4d-aaaf-30c8-4118-35d62ca794c9/202301101912182526-3497/BuildReport?accessString=f5b08d2aff2b4d6e1aa040341fc5e56e10005dbb0a06ab6fe3a1fa1903eb15d1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/aa268e4d-aaaf-30c8-4118-35d62ca794c9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by traya1** [comment]
Learn Build status updates of commit _[7de04ba](https://github.com/msbemba/memdocs/commits/7de04baae08d72d4b06cad4de191fddba3f09731)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[memdocs/intune/remote-actions/organizational-messages-prerequisites.md](https://github.com/msbemba/memdocs/blob/patch-186/memdocs/intune/remote-actions/organizational-messages-prerequisites.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/aa268e4d-aaaf-30c8-4118-35d62ca794c9/202301102035223364-3497/BuildReport?accessString=0e9a74b5c4caf50934c30d9eecd609ad591eb5ae1ee942c0ffc28519cfe71e67).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/aa268e4d-aaaf-30c8-4118-35d62ca794c9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by lenewsad** [comment]
#sign-off

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
