### PR TITLE
Update defender-advanced-threat-protection.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated windows 10 versions as 1607 is already EOS now.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by PRMerger8** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/9053

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@mestew Please review and Signoff this PR. Thanks.

**Review by aczechowski — APPROVED** [review]

**Pull request merged**
