### PR TITLE
Update app-sdk-ios.md

### PR DESCRIPTION
**Pull request by tranamst**
Updating app-sdk-ios.md  to tell consumers of static library to explictly weak link libSwiftAppleArchive.

Currently if you run the SDK Static Lib on iOS 15 simulator it can cause a crash since AppleArchive doesn't exist. This is fixed by explitclty weak linking apple archive in the main app target (by linking as "optional").

### CODE REVIEW

**Comment by Erikre** [comment]
Confirmed. Thanks for your contribution! #sign-off

**Comment by Erikre** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by tranamst** [comment]
@tiburd Is there anything else I need to do to merge this PR? Could you give me an ETA when this can be merged? Thank you!

**Pull request merged**
