### PR TITLE
Update windows-hello.md

### PR DESCRIPTION
**Pull request by ShrCaJesmo**
When the noted settings are applied, no chance to use WHfB sign-in, forced to use password. PIN available, but will fail. Removing settings allows use of WHFB sign-in methods.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@ShrCaJesmo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Brenduns** [comment]
Pending review with engineering.

**Comment by PRMerger16** [comment]
@ShrCaJesmo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Brenduns** [comment]
@ShrCaJesmo  We appreciate the time to draft and submit this PR. After getting feedback from PM for this area in Intune, we've decided not to accept this addition. This is core information for Windows Hello, which is best documented in there content. One thing we try to do is avoid documenting features or key interactions or limitations for other products in our docs.  While we are not looking to add this to our core docs, this could be added as a GitHub issue/comment on the article. That will remain attached to this article where others can find this.

**Pull request closed without merging**
