### PR TITLE
Information about autologon

### PR DESCRIPTION
**Pull request by schenardie**
Adding extra information about combining self deploying with autologon

### CODE REVIEW

**Comment by frankroj** [comment]
Thank you for the contribution @schenardie. I have made several corrections:

1) You mention the setting being a CSP, but it doesn't appear to be an actual existing CSP. Currently it's a custom OMA-URI. I have changed the wording accordingly.
2) You linked to the collect logs section of the doc but I think you meant to just link to the doc itself. I removed collect logs from the URL.
3) A few other minor corrections with links, style, and grammar.

With that said, although I think this is useful information, I'm not sure if this is the best place for this information. This section of the docs is meant for a more general explanation and overview of the feature. It's not intended for specific configuration under certain scenarios. I am thinking that possibly the FAQ might be a better fit for this info. Thoughts?

**Comment by schenardie** [comment]
Hi Frank. Agreed with the changes. About the location, where do you think that information should be?? I couldn't find a better place to place it.

**Comment by frankroj** [comment]
> Hi Frank. Agreed with the changes. About the location, where do you think that information should be?? I couldn't find a better place to place it.

I'm thinking maybe in the FAQ. Thoughts?

**Comment by schenardie** [comment]
I think that is fine, I'm mostly concerned that information is available to people, less much where. Do you want to add that or want me to move it?? Thanks Frank

**Comment by schenardie** [comment]
Hi Frank, I pushed another PR on Autopilot FAQ (https://github.com/MicrosoftDocs/memdocs/pull/4290) and will be closing this one. Thanks for the help.

**Pull request closed without merging**
