### PR TITLE
Update device-profile-troubleshoot.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the steps to Check the Status.

Fixes#https://github.com/MicrosoftDocs/memdocs/issues/3437

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by traya1** [comment]
Learn Build status updates of commit _[c39f5b0](https://github.com/msbemba/memdocs/commits/c39f5b04fc1d87a05e283557a9e40f1c29584118)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[memdocs/intune/configuration/device-profile-troubleshoot.md](https://github.com/msbemba/memdocs/blob/patch-180/memdocs/intune/configuration/device-profile-troubleshoot.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/aa268e4d-aaaf-30c8-4118-35d62ca794c9/202212131628286242-3451/BuildReport?accessString=01f9823e7d72ce76b2f4b52323fda7b9cf203667f8b6f6355a0bed9e93c75a3a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/aa268e4d-aaaf-30c8-4118-35d62ca794c9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by MandiOhlinger** [comment]
@msbemba Hey - Settings > Sync is still correct. So, maybe update the text to add both.

**Comment by msbemba** [comment]
> Settings > Sync

I have added both the steps to the document. Thank you.

**Comment by traya1** [comment]
Learn Build status updates of commit _[98a7fe5](https://github.com/msbemba/memdocs/commits/98a7fe526d798977e5add91561067d16e046543f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[memdocs/intune/configuration/device-profile-troubleshoot.md](https://github.com/msbemba/memdocs/blob/patch-180/memdocs/intune/configuration/device-profile-troubleshoot.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/aa268e4d-aaaf-30c8-4118-35d62ca794c9/202212140627511325-3451/BuildReport?accessString=e8ebd2dee473a8c16d4dd829dac99161af880d2f747131ed7f434d29f3c33df1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/aa268e4d-aaaf-30c8-4118-35d62ca794c9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Review by MandiOhlinger — APPROVED** [review]

**Pull request merged**
