### PR TITLE
Update device-enrollment-program-enroll-ios.md

### PR DESCRIPTION
**Pull request by Leicham**
added a note to enrollment profiles to highlight enrollment restrictions could block automated enrollment, regardless of user attestation if the platform is blocked

### CODE REVIEW

**Comment by PRMerger10** [comment]
@Leicham : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@ErikjeMS Could you review the proposed update? I got ahead of myself with edits (I lost track of the queue I was working in).

**Comment by ErikjeMS** [comment]
#sign-off

**Pull request merged**
