### PR TITLE
Missing step

### PR DESCRIPTION
**Pull request by thommck**
The path to setting up a device type restriction missed a step

### CODE REVIEW

**Comment by PRMerger13** [comment]
@thommck : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by MandiOhlinger — APPROVED** [review]

**Comment by MandiOhlinger** [comment]
@thommck You are correct. Thank you! #sign-off

**Comment by PRMerger12** [comment]
@MandiOhlinger: I'm sorry - only the author of this article, @ErikjeMS, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
