### PR TITLE
Update device-inventory.md

### PR DESCRIPTION
**Pull request by msbemba**
Added Windows to the list of platforms were the wi-fi ipv4 setting is available per issue#https://github.com/MicrosoftDocs/memdocs/issues/2914

### CODE REVIEW

**Comment by PRMerger4** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by yogkumgit** [comment]
@Smritib17 Please review and Signoff this Pr. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Smritib17 Gentle reminder

**Review by Smritib17 — APPROVED** [review]

**Comment by Smritib17** [comment]
#sign-off

**Pull request merged**
