### PR TITLE
Update install-modules.md

### PR DESCRIPTION
**Pull request by andrew-s-taylor**
Updated for new version of the module

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by frankroj** [comment]
@andrew-s-taylor waiting on some feedback from Product Group since some of the changes recommended by you are different than those suggested by Product Group.

**Comment by andrew-s-taylor** [comment]
@microsoft-github-policy-service agree

**Comment by frankroj** [comment]
Waiting on PG approval before merging

**Comment by frankroj** [comment]
[MAXADO-7983765](https://office.visualstudio.com/MAX/_workitems/edit/7983765)

**Comment by frankroj** [comment]
#sign-off

**Pull request merged**
