### PR TITLE
Update apps-add-office365-macOS.md

### PR DESCRIPTION
**Pull request by Base51**
including OneDrive as deployed application.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@Base51 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by lenewsad — APPROVED** [review]

**Comment by lenewsad** [comment]
@Erikre I confirmed/approved this change--can you please sign off when you have a moment? Thanks!

**Comment by PRMerger13** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@lenewsad I'll merge the pull request with your approval. Thanks for the review.

**Pull request merged**
