### PR TITLE
Update enhanced-http.md

### PR DESCRIPTION
**Pull request by sccmentor**
I've added in the link to Azure services onboarding as I think that helps. I'm not sure how the linking works, I've tested and it's a dead link. So if you can assist with entering the correct link then that would be really helpful

### CODE REVIEW

**Comment by PRMerger14** [comment]
@sccmentor : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@aczechowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by aczechowski — APPROVED** [review]
Thanks @sccmentor for the contribution! I agree that's a good reference. I made a tweak to the link format.

**Comment by aczechowski** [comment]
#sign-off

**Pull request merged**
