### PR TITLE
Update devices-wipe.md

### PR DESCRIPTION
**Pull request by msbemba**
Low level delete/format means the data cannot be recovered and that is what happens in remote wipe. made changes accordingly as the standard delete process lets the user recover data.

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/memdocs/issues/3033

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Smritib17 Please review and signoff this PR. Kindly ensure that  ready-to-merge label is added. Thanks

**Comment by deadthirsty** [comment]
@msbemba This isn't true. Data can easily be recovered after a wipe, as described here: 
https://call4cloud.nl/2022/03/ill-always-know-what-you-did-last-wipe/

This sentence should describe to Intune admins the method that "wipe" uses to remove the data is a simply a file deletion, and that the drive is BitLocker decrypted as part of this process. Your proposed changes elude to this being a "secure" wipe, where's that's not the case.

This official documentation is more realistic description of exactly what happens as part of a PBR: https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/how-push-button-reset-features-work?view=windows-11#remove-everything?id=5004252

**Comment by rudyooms84** [comment]
Mmm... "Low level delete/format means the data cannot be recovered and that is what happens in remote wipe" are you 100% sure about this?

I wrote that blog on call4cloud.nl some time ago and when looking at what happens when performing a wipe now...  At which point in time or with which update did this behavior changed? (if it even changed?)

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@deadthirsty and @rudyooms84 The author has updated the document to reflect below. This change will be updated shortly.

"The method that "Wipe" uses to remove data is simple file deletion, and the drive is BitLocker decrypted as part of this process."

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
