### PR TITLE
Update device-limit-intune-azure.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the chart for intune limitations as Intune limits do notapply for GPO

Fixes https://github.com/MicrosoftDocs/memdocs/issues/4240

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@lenewsad Please review and signoff this PR. Thanks

**Comment by lenewsad** [comment]
Hi @msbemba @yogkumgit, in review with the PM.

**Comment by yogkumgit** [comment]
@lenewsad Kindly update.

**Review by lenewsad — APPROVED** [review]
approving to align with other section since this is conflicting info.

**Comment by lenewsad** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
