### PR TITLE
Update apps-win32-app-management.md

### PR DESCRIPTION
**Pull request by 38cat**
Intune Management Extension can using on Azure AD Registered device.
I want you to write it easy to understand.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@38cat : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by 38cat** [comment]
Hi  @Erikre Erikre
I added line 115, below.
"When device is  enrolled by Azure AD registered,  you need to select **System**."

If Azure AD Registered device, I think required system context.
Please, confirm.

**Comment by 38cat** [comment]
How is it going?

**Review by Erikre — APPROVED** [review]

**Comment by Erikre** [comment]
@38cat - Thanks for the contribution. Adding now. #sign-off

**Comment by PRMerger19** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
