### PR TITLE
Isn't syncDisabled the opposite?

### PR DESCRIPTION
**Pull request by reiikei**
In my understanding, if syncDisabled is set as "true", Edge sync will be disabled.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@reiikei : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@Erikre : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Erikre** [comment]
@reiikei - Thank you for the feedback and suggestion. I'm having this published today.

**Comment by Erikre** [comment]
#sign-off

**Pull request merged**
