### PR TITLE
Update setup-cloud-management-gateway.md

### PR DESCRIPTION
**Pull request by dctardy**
Added this comment to support security documentation required for customers that are sensitive to storage accounts available to the Internet.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@dctardy : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @dctardy for the contribution 😄 
I like it, but I want to put this note in another article, so give me a bit to massage it and find a better home.

**Comment by PRMerger20** [comment]
@aczechowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
I moved the note over to the Plan for CMG article where it talks about the components. I get the thought to put it inline with the steps to setup, but I think it makes more sense to group it with the other components.

#sign-off

**Pull request merged**
