### PR TITLE
Update device-restrictions-android-for-work.md

### PR DESCRIPTION
**Pull request by msbemba**
Email address is mandatory as there is an error stating that the value must not be empty. updated the document accordingly.

Per issue#https://github.com/MicrosoftDocs/memdocs/issues/2979

### CODE REVIEW

**Comment by PRMerger17** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by MandiOhlinger — APPROVED** [review]

**Comment by MandiOhlinger** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
