### PR TITLE
Updating this page based on Engineering Insights investigation

### PR DESCRIPTION
**Pull request by aanavath**
This one doesn't need additional review

### CODE REVIEW

**Comment by PRMerger9** [comment]
@aanavath : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@Brenduns : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @aanavath - This pull request was opened in the public repo. PMs should work in the private repo, per the Microsoft Docs contributor guide. Would you make this content update in the private repo instead? Thank you! We'll close this PR.

**Comment by ktoliver** [comment]
@Brenduns Just saw that you made an edit. We can process this PR here. Will watch for your sign-off.

**Comment by ktoliver** [comment]
@aanavath Would you make future content updates in the private repository? Thanks!

**Comment by Brenduns** [comment]
@ktoliver  Thanks!

#sign-off  The link is fixed and functional.

**Comment by ktoliver** [comment]
@brenduns I'm not able to verify the links because they are relative repo-level links (example: /intune/protect/file) instead of relative file-based links for files that are in the same repo (example: file.md or ../file.md). I know that the former link types are used to point to files in other Microsoft Docs repos; is there an advantage to doing it for articles that are in the same repository? (The downside from a PR review perspective is that the repo-level links can't be tested in public repo PRs without pasting the content into a personal test environment. Whereas, same-repo relative links click through in GitHub preview.) Just curious. Thanks!

**Pull request merged**
