### PR TITLE
Update windows-10-expedite-updates.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the prerequisites to reflect EMS E3 as windows 10 quality updates works on Win 10 Pro as well and If the W10 Enterprise E3 license were applied, the edition would no longer be Pro it would be Enterprise.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by PRMerger4** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/memdocs/issues/1682

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
