### PR TITLE
User Affinity moved on "Settings" tab

### PR DESCRIPTION
**Pull request by Yogesh-Shede**
Hi, Since "User Affinity" option has been moved on "Settings" tab please make propose changes as this will be helpful for everyone.
Also add new screen shot attached here on row number  64 

Screenshot of the create profile screen with Enroll with user affinity selected

### CODE REVIEW

**Comment by PRMerger18** [comment]
@Yogesh-Shede : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@ErikjeMS Could you review the proposed updates? 

Image files need to be added to the repository in a pull request; we can't link to images that are hosted elsewhere. Thanks.

**Comment by Yogesh-Shede** [comment]
@ktoliver  thanks for your reply. Image is added in pull request already. I hope this can be seen by reviewer also ?

**Comment by ktoliver** [comment]
@Yogesh-Shede Hi, the image needs to be added to the pull request as a physical file, so the file is added to the repository. But after the author reviews the PR, the PR review team can help with this (move the commit to the private repo and create a new image file from the screenshot).

**Comment by ErikjeMS** [comment]
#sign-off

**Comment by ktoliver** [comment]
We'll move this commit and create an image file to add in the PR in the private repo. We'll post here when finished.

**Comment by ktoliver** [comment]
Hi @Yogesh-Shede The screenshot you provided is taken using the Dark theme in GitHub. Could you provide one what uses Light theme to match the screenshot that precedes the one you added?

image

image

Also, the red outline should have square corners, not rounded corners, if you could, as in the top image in the screenshot I added in this comment.

Thanks!

**Comment by Yogesh-Shede** [comment]
> Hi @Yogesh-Shede The screenshot you provided is taken using the Dark theme in GitHub. Could you provide one what uses Light theme to match the screenshot that precedes the one you added?
> 
> image
> 
> image
> 
> Also, the red outline should have square corners, not rounded corners, if you could, as in the top image in the screenshot I added in this comment.
> 
> Thanks!

@ktoliver  please check attached light theme screenshot as requested.
Basic Tab

**Pull request closed without merging**
