### PR TITLE
Update azure-virtual-desktop-multi-session.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the document removing the duplicated text

### CODE REVIEW

**Comment by msbemba** [comment]
issue#https://github.com/MicrosoftDocs/memdocs/issues/2270

**Comment by PRMerger4** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@dougeby Please review and merge this PR. Thanks

**Pull request merged**
