### PR TITLE
Update macos-enroll.md

### PR DESCRIPTION
**Pull request by msbemba**
removed VMware Fusion from Apple silicon section as it is not supported

reference https://kb.vmware.com/s/article/90364

Fixes https://github.com/MicrosoftDocs/memdocs/issues/3873

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by lenewsad** [comment]
Hi @arnabbiswas @beflamm, could you please review this change?

**Comment by lenewsad** [comment]
Hi @msbemba, approved by the PM. They also requested more details to the VMware Fusion section, "VMware Fusion is only supported on Intel Macs. "

**Review by lenewsad — APPROVED** [review]

**Comment by lenewsad** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@msbemba Please update.

**Comment by msbemba** [comment]
@yogkumgit The changes were already made. We are good to merge

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
