### PR TITLE
Update manage-microsoft-edge.md

### PR DESCRIPTION
**Pull request by Base51**
com.microsoft.intune.mam.managedbrowser.disableShareBrowsingHistory (changed from man to mam)
and
com.microsoft.intune.mam.managedbrowser.disabledFeatures (changed from disable to disabled)

### CODE REVIEW

**Comment by PRMerger16** [comment]
@Base51 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@Base51 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Erikre** [comment]
@Base51 - Thanks for the contribution!

**Comment by Erikre** [comment]
#sign-off

**Comment by Base51** [comment]
It´s also necessary to change from **disable** to **disabled** on password and inprivate, also remove the blank space inside the note.
image
image
image

**Pull request merged**
