### PR TITLE
Update ios-ipados-personal-device-security-configurations.md

### PR DESCRIPTION
**Pull request by msbemba**
According to the Device Restrictions docs: https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-ios#built-in-apps
These settings do not apply to personal device enrollment

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/memdocs/issues/2515

**Comment by PRMerger14** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@lenewsad Please merge this PR. Thanks

**Comment by lenewsad** [comment]
Hi @AnyaNovicheva1, can you help us confirm that the doc change is correct? Some information was removed because it may not be applicable to personal devices. Thank you!

**Comment by AnyaNovicheva1** [comment]
Ben Flamm is the owner of device configuration for Apple MDM and would know the answer here. @beflamm

**Comment by yogkumgit** [comment]
@beflamm Please review and signoff. Thanks

**Comment by beflamm** [comment]
Hi @yogkumgit @lenewsad @msbemba - these settings **do apply** to personal devices and are available for devices enrolled using User Enrollment (screenshots attached):

Apple Dev Documentation:
image

Testing on personal device:
IMG_0001 (002)

**Comment by yogkumgit** [comment]
@lenewsad Kindly Signoff

**Comment by beflamm** [comment]
Can we get clarification on the issue copied below? These settings are available for User Enrollment and don't require supervision. I successfully tested these settings on a personally owned device.

_"These settings do not apply to Apple User Enrollments, which is likely to be a personal device enrollment. If those settings are indeed pushed with the personal security configuration, then there should be a notice that mention that if the personal device was enrolled using the Apple User Enrollment method these settings would not take effect."_

**Comment by lenewsad** [comment]
@yogkumgit @msbemba @JohanFreelancer9 The PM, @beflamm, says that these settings do apply to personal devices so the content contribution doesn't fit here.

**Comment by msbemba** [comment]
@lenewsad and @beflamm 

Sorry about the confusion. This is what the intune portal shows up and what made the customer raise the issue. Do we have to work with the product group to change options in the portal?

image

Thanks
Sri

**Comment by lenewsad** [comment]
Hi @msbemba Yes, I'll open a bug with the product team.

**Comment by lenewsad** [comment]
@msbemba Closing b/c PM confirmed no UI changes will be made right now. He updated [the other doc](https://docs.microsoft.com/en-us/mem/intune/configuration/device-restrictions-ios#built-in-apps) so the doc info is all correct.

**Pull request closed without merging**
