### PR TITLE
Update dfci-management.md

### PR DESCRIPTION
**Pull request by pelarsen**
Added Surface Registration Support for Windows Autopilot as a method to register surface devices to leverage DCFI

### CODE REVIEW

**Comment by PRMerger16** [comment]
@pelarsen : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by PRMerger13** [comment]
@greg-lindsay : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by greg-lindsay** [comment]
The sentence said that OEMs can register, and in this case Microsoft is the OEM so it's redundant to include this as a third option.  I've restructured the wording a bit.

**Pull request merged**
