### PR TITLE
"Shell" scripts and screenshot update

### PR DESCRIPTION
**Pull request by Yogesh-Shede**
Hi,
Please update screenshot and "Shell" word on below link.

Link > https://docs.microsoft.com/en-us/mem/intune/apps/macos-shell-scripts#create-and-assign-a-shell-script-policy

### CODE REVIEW

**Comment by PRMerger18** [comment]
@Yogesh-Shede : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Yogesh-Shede** [comment]
Hi, Any update on this ?

**Comment by Yogesh-Shede** [comment]
Hi, Any update on this ?

**Comment by PRMerger13** [comment]
@Erikre : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Erikre — APPROVED** [review]

**Comment by Erikre** [comment]
@Yogesh-Shede - Thank you for the contribution. Publishing this change now.

**Comment by Erikre** [comment]
#sign-off

**Pull request merged**
