### PR TITLE
Update store-apps-microsoft.md

### PR DESCRIPTION
**Pull request by msbemba**
Added more information on which admins can add and deploy a store app. If there are any other RBAc roles, let me know we can add that as well.

Fixes https://github.com/MicrosoftDocs/memdocs/issues/3934

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — CHANGES_REQUESTED** [review]
Copy review.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Erikre Please review and sign off this PR. Thanks

**Comment by yogkumgit** [comment]
@Erikre Gentle reminder.

**Review by Erikre — APPROVED** [review]

**Comment by Erikre** [comment]
#sign-off

**Review by Erikre — APPROVED** [review]

**Pull request merged**
