### PR TITLE
Update advanced-threat-protection-configure.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the navigation as it is not Microsoft defender for endpoint admin console.

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/memdocs/issues/2613

**Comment by Brenduns** [comment]
#hold-off 

@msbemba   This PR is not approved.   Here is a capture from the live Tenant this morning. The link title is "Open the Microsoft Defender Security Center"   Note this is very far down the page.    If this link doesn't appear for the customer, they should open a support incident to investigate why their tenant does not present this.   

image

**Comment by msbemba** [comment]
Thank you @Brenduns .I checked in a couple of tenants and I see the below

**Comment by msbemba** [comment]
I was under the impression that what I see currently is the latest as it was previously called the Microsoft Defender Security Center( as updated in the document).

**Comment by Brenduns** [comment]
@msbemba  Interesting.   I'm pinging the dev/PM about this.      Stay tuned.  Meanwhile: Does your tenant already have the connection to Defender set up?  It appears to - though I don't have that set up myself  and a loaner from the Dev isn't connecting today.  I wonder if the pre/post connection to MDE affects that link text in the UI.  While  not delving into troubleshooting (which we need to avoid doing), I wonder if its a change in text label seen before/after that connection to Defender is configured. I also wonder if they just didn't see it as its ridiculously far down the page.  If they saw the link, (either form), they might have mentioned the link they do see.

**Comment by msbemba** [comment]
@Brenduns That is correct and I have confirmed with a couple of other tenants and I see the same result.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by Brenduns** [comment]
#sign-off 

It seems MDE has some changes that haven't filtered to all content or been generally discussed in docs (that I've found).  Typically, the Security Center is has been a Discrete console used for all Security Operations, with a change being that the Defender for Endpoint admin console seems to now be co-located in that Security Center.  The standalone console for MDE was deprecated and there are now link redirections in place.

**Pull request merged**
