### PR TITLE
Add note about multiple users

### PR DESCRIPTION
**Pull request by paulwetter**
Added note her about multiple logged on users and task sequences not showing in Software Center.

Per Aaron's suggestion on Twitter to add this in a more visible place.  There are a few other docs where it may make sense, but many link to this one.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@paulwetter : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by aczechowski — APPROVED** [review]
Thanks @paulwetter, this looks good. And THANK YOU for your first contribution to MEMDocs 😄 🎉

**Comment by aczechowski** [comment]
#sign-off

**Comment by ktoliver** [comment]
@aczechowski Would it be more precise--and accurate--to say that "task sequence deployments might not appear in Software Center until all users are signed out"?

**Comment by paulwetter** [comment]
In a quick test, If User1 logs in and then User2 logs in remotely which disconnects User1 (but not logs off), task sequences are not available for User2 and still available for User1 (by way of disconnecting but not logging off User2).  However, if User2 logs User1 off in task manager, task sequences almost immediately appear for User2 in Software Center (no refresh or intervention needed).  So, it seems if you get it down to 1 user.  That user will have them available.

**Comment by aczechowski** [comment]
@ktoliver thanks for asking. Paul's borrowing language from https://docs.microsoft.com/mem/configmgr/osd/deploy-use/deploy-a-task-sequence (step 5 for deployment settings, which per the Twitter discussion is a bit buried). If *all users* are signed out, then there's no one to see the deployment in Software Center. 😉 I'm ok with his wording, although an alternative would be to strike the last phrase ("until additional users are logged off") and just end the sentence after Software Center (as in the other article). Without that last phrase, it's *implied* that deployments won't show when multiple users are signed in, so not as precise but still accurate.

**Comment by ktoliver** [comment]
I understand now! I'll make an edit to left-align the note and then merge. Thanks, all!

**Comment by PRMerger5** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@paulwetter @aczechowski Is this OK or does it need adjustment?

image

**Comment by paulwetter** [comment]
@ktoliver looks good to me.  Thanks!

**Comment by ktoliver** [comment]
> @ktoliver looks good to me. Thanks!

Thanks @paulwetter. I'll merge.

**Pull request merged**
