### PR TITLE
Update reports-api-url.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the URL

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/memdocs/issues/2901

**Comment by PRMerger4** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Erikre Please review and signoff this PR. Thanks

**Comment by yogkumgit** [comment]
@Erikre Gentle reminder

**Comment by Erikre** [comment]
This FWLink needs to be used rather than a hardcoded link. Closing.

**Comment by msbemba** [comment]
@

**Comment by msbemba** [comment]
@Erikre We do not have access to create FW link. Could you please help us with one sot hat I can update the document?

CC: @yogkumgit 

Thanks
Sri

**Review by Erikre — APPROVED** [review]

**Comment by Erikre** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this Pr. Thanks

**Pull request merged**
