### PR TITLE
Windows 10 Pro is not supported for PR

### PR DESCRIPTION
**Pull request by JankeSkanke**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@JankeSkanke : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@mestew for review

Thanks.

**Comment by aczechowski** [comment]
Based on side-thread with Jan & PM Avi, I'm closing this PR. Avi might make some changes to the article based on the discussion.

**Pull request closed without merging**
