### PR TITLE
Added information about physical, virtual machines

### PR DESCRIPTION
**Pull request by fox-on-the-run**
Based on customer feedback I called out the install options on Virtual and Physical machines, as well as the supported processor architecture

### CODE REVIEW

**Comment by Brenduns** [comment]
#sign-off

**Comment by Brenduns** [comment]
@Lenewsad   Hi Laura, can you sign-off on this article edit?  I've been working with the Author and this is correct.

**Comment by lenewsad** [comment]
#sign-off

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Comment by tiburd** [comment]
@fox-on-the-run
Hi Lothar,
This pull request was opened in the public repo. PMs and content developers should work in the private repo, as described in [the authoring guide](https://review.docs.microsoft.com/en-us/Office-Authoring-Guide/office-docs-authoring-overview?branch=main). We reviewed and merged this PR but encourage you to use the private repo for future contributions to Microsoft Learn.

At your earliest convenience, please also complete your account setup so that your GitHub and Microsoft accounts are connected:
- [Set up your accounts](https://review.docs.microsoft.com/en-us/office-authoring-guide/contribute-get-started-setup-github-ro?branch=main)

Thank you!

**Pull request merged**
