### PR TITLE
Update enroll-your-device-in-intune-macos-cp.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to point 5 settings window "opens"

Fixes https://github.com/MicrosoftDocs/memdocs/issues/4070

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Comment by lenewsad** [comment]
#hold-off

**Comment by lenewsad** [comment]
@msbemba @yogkumgit No changes are needed. After you click "download profile" the macOS system settings open in a new window.

**Review by lenewsad — CHANGES_REQUESTED** [review]
No changes necessary. The system settings open in a new window.

**Pull request closed without merging**
