### PR TITLE
Update intune-endpoints.md

### PR DESCRIPTION
**Pull request by msbemba**
"*.manage.microsoft.com" is not enough since it does not include "manage.microsoft.com"

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by PRMerger12** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/memdocs/issues/2579

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by Smritib17 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
