### PR TITLE
Update store-apps-company-portal-app.md

### PR DESCRIPTION
**Pull request by msbemba**
Added direct download link in case users cannot see in the store.

Fixes https://github.com/MicrosoftDocs/memdocs/issues/3994

### CODE REVIEW

**Review by JohanFreelancer9 — CHANGES_REQUESTED** [review]
Copy review.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Erikre Please review and signoff this PR. Thanks

**Comment by yogkumgit** [comment]
@Erikre Gentle reminder

**Comment by Erikre** [comment]
#sign-off

**Review by Erikre — APPROVED** [review]

**Comment by Erikre** [comment]
#sign-off

**Pull request merged**
