### PR TITLE
Update multi-factor-authentication.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated step 8 as  **Require device to be marked as compliant** might not be necessary in this particular case of Require multifactor authentication for Intune device enrollment

fixes#https://github.com/MicrosoftDocs/memdocs/issues/3482

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by traya1** [comment]
Learn Build status updates of commit _[135ae1f](https://github.com/msbemba/memdocs/commits/135ae1fa84bf8674de644425ca653dfd40c5f668)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[memdocs/intune/enrollment/multi-factor-authentication.md](https://github.com/msbemba/memdocs/blob/patch-185/memdocs/intune/enrollment/multi-factor-authentication.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/aa268e4d-aaaf-30c8-4118-35d62ca794c9/202301101740286456-3496/BuildReport?accessString=d756cf9c7fa8241d2d93911f7c1eb1b50e135e34d717d6dcd64763b7d9b098b3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/aa268e4d-aaaf-30c8-4118-35d62ca794c9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@lenewsad Please review and sign off this PR. Thanks

**Comment by lenewsad** [comment]
Hi @msbemba, I confirmed that no doc changes are needed. The setting in question should remain in the docs. This setting implements device compliance status, and ensures that the device isn't marked compliant until it meets all conditions for access. In this case, the condition is multifactor authentication. Once the person completes multifactor authentication, their device will be marked compliant and they'll be able to complete enrollment.

**Pull request closed without merging**
