### PR TITLE
Collection cloud sync is no longer a pre-release feature.

### PR DESCRIPTION
**Pull request by davidpaMSFT**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@davidpaMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by aczechowski — APPROVED** [review]
Thanks @davidpaMSFT for catching this and making the edit!

**Comment by aczechowski** [comment]
#sign-off

**Pull request merged**
