### PR TITLE
Update quickstart-setup-auto-enrollment.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the navigation

Fixes https://github.com/MicrosoftDocs/memdocs/issues/3859

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@lenewsad Please review and sign off this PR. Thanks

**Comment by lenewsad** [comment]
Hi @msbemba, thanks for the edit. I don't see the Settings option, but there is a more universal path I was able to confirm. Here is the updated path: 

**All services** > **M365 Azure Active Directory** > **All services** > **Azure Active Directory** >  **Mobility (MDM and MAM)**

If a customer were to add the Azure Active Directory to their favorites, it would remove the 2nd **All services** step b/c Azure Active Directory would be moved up front to their dashboard. But if it isn't favorited, then they need to go to **All services**.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@lenewsad Yes, I was able to navigate now with All services > M365 Azure Active Directory > All services > Azure Active Directory > Mobility (MDM and MAM)

Thanks
Sri

**Comment by lenewsad** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
