### PR TITLE
Update enrollment-autopilot.md

### PR DESCRIPTION
**Pull request by andrew-s-taylor**
Changed contains to startsWith

### CODE REVIEW

**Comment by frankroj** [comment]
Thank you for the contribution @andrew-s-taylor. Is there a specific reason for the change to the query? It would seem that either query will work, so there's not a specific reason to change it to the alternate method you suggest. If you do have a specific reason, please let me know.

**Comment by andrew-s-taylor** [comment]
Hi @frankroj it is based on this Twitter thread where contains has been removed from the GUI for performance issues
https://twitter.com/panusaukko/status/1732826277806051726

**Comment by frankroj** [comment]
Thanks for the context @andrew-s-taylor. I saw that Jason Sandys replied so that is pretty golden. Let me just confirm one or two other places and then I'll approve the changes.

**Comment by frankroj** [comment]
Confirmed with Jason Sandys. Also tested change in query in my tenant and confirmed it works. Approving change.

**Comment by frankroj** [comment]
Thanks again @andrew-s-taylor for the contribution and letting us know about this issue in docs. I have gone ahead and approved both PRs that you submitted. The changes should go live later today.

**Comment by frankroj** [comment]
#sign-off

**Pull request merged**
