### PR TITLE
Update deploy-applications.md

### PR DESCRIPTION
**Pull request by andrewjohnporter**
Added more detail to the Install Behaviour deployment information

### CODE REVIEW

**Comment by PRMerger13** [comment]
@andrewjohnporter : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@aczechowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by aczechowski — APPROVED** [review]
Thanks @andrewjohnporter for the contribution, and thank you for your first contribution to MEMDocs! 😄 🎉
I made a few tweaks for style and clarity, but otherwise look good.

**Comment by aczechowski** [comment]
#sign-off

**Pull request merged**
