### PR TITLE
Update task-sequence-steps.md

### PR DESCRIPTION
**Pull request by gwblok**
Added information about the SMSTSUninstallCCMClient Variable which controls the Full Removal of the CM Client in a Task Sequence.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@gwblok : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @gwblok for the contribution. Let me check with the engineering team. We purposefully don't doc some task sequence variables. 😉

**Review by aczechowski — APPROVED** [review]
Thanks @gwblok for the contribution! I made a few tweaks for style, and clarified that it only applies to OSD task sequence, and happens after next restart. Thanks for the edit!

**Comment by aczechowski** [comment]
#sign-off

**Pull request merged**
