### PR TITLE
Added Note to Cloud-based sources section

### PR DESCRIPTION
**Pull request by Stroell**
If the mentioned option is not set, Microsoft Update cannot be used as source

### CODE REVIEW

**Comment by PRMerger18** [comment]
@Stroell : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@aczechowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by aczechowski — APPROVED** [review]
Thanks @Stroell for the contribution! A good tip to add.
Meghan is out, so I'm approving this on her behalf.

**Comment by aczechowski** [comment]
@ktoliver can you please review and merge? Meghan is out. I reviewed and approve the change. Most of the content under the /core folder is shared between the two of us. 😄

**Comment by ktoliver** [comment]
@aczechowski Thanks for the review.

**Pull request merged**
