### PR TITLE
Windows 10 mobile is not supported now.

### PR DESCRIPTION
**Pull request by 38cat**
I think don't need below.
---
> [!IMPORTANT]
> Windows 10 mobile devices don't support co-management.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@38cat : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by 38cat** [comment]
Additional : In Japanese, "Windows 10 mobile" is translated "Windows 10".
image

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by aczechowski** [comment]
Thanks @38cat for taking the time to make this contribution and provide the localization feedback.

Re the note itself, I think for now we do need to keep it. ConfigMgr does currently still support mobile devices via on-premises MDM and the Exchange connector. Specifically the Windows 10 IoT Mobile Enterprise edition. See https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/configs/supported-operating-systems-for-clients-and-devices#bkmk_OnpremOS

Re the localization, I think that's accurate. "Windows 10" is the brand, which don't get localized. In this instance, it's not referring to "Windows 10 Mobile" but "Windows 10 mobile devices." Or are you saying that in Japanese, the outcome is basically "Windows 10 devices" and the "mobile" part is getting swallowed?

I'm going to close this pull request, as again, I think we need to keep the note. With it closed you should still be able to comment, so let me know if you disagree. :) And I'm curious about the localization as well. Thanks!

**Comment by 38cat** [comment]
@aczechowski 
Thank you your reply!

I think why don't you write "Windows 10 IoT Mobile Enterprise"?

Just as you say,  In Japanese, the "mobile" part is getting swallowed,
display "Windows 10 device is not supported co-management."

**Comment by aczechowski** [comment]
Thanks @38cat 
I'm checking with another source to verify, "Windows 10 IoT Mobile Enterprise" may be unsupported now as well. If I can confirm that, then I'll reopen this PR and approve it. Then we'll work to get it removed from our list of supported client OSes.
I'll followup with our localization folks as to why mobile it dropped. Thank you for sharing that feedback!

**Comment by aczechowski** [comment]
Ah, I confirmed that "Windows 10 IoT Mobile Enterprise" and "Windows 10 Mobile Enterprise" are binary equivalents, and the latter is out of support since January 2020: https://docs.microsoft.com/lifecycle/products/windows-10-mobile-enterprise-released-in-october-2017
Reopening this PR. Thank you @38cat for the contribution! 🎉

**Review by aczechowski — APPROVED** [review]

**Comment by aczechowski** [comment]
#sign-off

**Comment by 38cat** [comment]
@aczechowski Thank you for your confirm.
I'm glad to be clear that "Windows 10 IoT Mobile Enterprise" and "Windows 10 Mobile Enterprise" are equivalents.

Sorry, my first message was poor and my English is bad. I try to write in detail next time.
I hope to be docs better.

Thanks!

**Comment by aczechowski** [comment]
@38cat no need to apologize, your English is way better than my Japanese, which is zero. 😁

**Comment by TinaMcN** [comment]
@38cat この問題を報告していただきありがとうございます。機械翻訳ツールの問題のようです。  私は人間の翻訳のために記事を送った。 (Thank you for reporting this issue. It appears to be a problem with our machine translation tool. I sent the article to be human translated.)

**Pull request merged**
