### PR TITLE
Packages and Programs Maintenance Window note

### PR DESCRIPTION
**Pull request by ChadSimmons**
The note says

> "If you use maintenance windows on the same collection to which you deploy this program.."

This is misleading since maintenance windows apply to the client computer, not a specific collection or deployment.

The updated language clarifies this.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by BalaDelli — APPROVED** [review]

**Comment by BalaDelli** [comment]
#sign-off

**Comment by dereklangMSFT** [comment]
Maintenance windows are targeted to collections. Devices inherit the maintenance window policy via the collections they are members of, but maintenance windows are not targeted directly to devices.

**Comment by ChadSimmons** [comment]
> Maintenance windows are targeted to collections. Devices inherit the maintenance window policy via the collections they are members of, but maintenance windows are not targeted directly to devices.

Yes, that is much more clear than my original comment.  Still, I think the PR language clarifies the original text.  Agree?

**Comment by BalaDelli** [comment]
#sign-off

**Comment by dougeby** [comment]
This was signed-off on but not merged. Merging.

**Pull request merged**
