### PR TITLE
Update supported MTD protocols

### PR DESCRIPTION
**Pull request by chadseippel**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@chadseippel : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Erikre — APPROVED** [review]

**Comment by Erikre** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@Erikre : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Erikre** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
While adding a comma in the update, I noticed that the two images weren't displayed in GitHub preview because of capital letters in the image references:

image

I fixed it here by changing "UI" in the image reference file name to match "ui" in the file name in the repo. Thanks.

**Pull request merged**
