### PR TITLE
Update app-sdk-ios.md

### PR DESCRIPTION
**Pull request by chadseippel**

### CODE REVIEW

**Comment by PRMerger5** [comment]
@chadseippel : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by Erikre — APPROVED** [review]

**Comment by Erikre** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
