### PR TITLE
note for illegal chars

### PR DESCRIPTION
**Pull request by MattShadboltMSFT**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@MattShadboltMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ErikjeMS** [comment]
@MattShadboltMSFT Can you close this PR and reopen in the private repo? The build team requires that internal MS employees make their changes in in the private repo.

**Comment by ErikjeMS** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
We'll merge the PR here because it's signed off. PMs are asked to work in the private repo. @MattShadboltMSFT Let me know if you need information about how to do that; I can email it to you. Thanks.

**Comment by MattShadboltMSFT** [comment]
Would really appreciate if you could provide this information.

Thanks
Matt

**Pull request merged**
