### PR TITLE
Update manage-office-365-proplus-updates.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the CDN base URL's 
reference 
https://techcommunity.microsoft.com/t5/office-365-blog/how-to-manage-office-365-proplus-channels-for-it-pros/ba-p/795813

### CODE REVIEW

**Comment by PRMerger16** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by JohanFreelancer9** [comment]
@msbemba,  Just a suggestion - I think the heading should be "CDN base URL". If you agree, please change it. Thanks.

**Comment by msbemba** [comment]
The attribute is one word. So I had mentioned the same

image

**Pull request merged**
