### PR TITLE
Screenshot added and minor change

### PR DESCRIPTION
**Pull request by Yogesh-Shede**
Screenshot added and minor change for "Device diagnostics" on below link 
https://docs.microsoft.com/en-us/mem/intune/remote-actions/collect-diagnostics#disable-device-diagnostics

### CODE REVIEW

**Comment by PRMerger15** [comment]
@Yogesh-Shede : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ErikjeMS** [comment]
#sign-off

**Comment by ktoliver** [comment]
We'll move this commit and create an image file to add in the PR in the private repo. We'll post here when finished.

**Comment by ktoliver** [comment]
Hi @Yogesh-Shede The screenshot you provided is taken using the Dark theme in GitHub. Could you provide one what uses Light theme to match the screenshot that precedes the one you added?

image

image

Thanks!

**Comment by Yogesh-Shede** [comment]
> Hi @Yogesh-Shede The screenshot you provided is taken using the Dark theme in GitHub. Could you provide one what uses Light theme?
> 
> image
> 
> image
> 
> Thanks!
@ktoliver  please check attached light theme screenshot as requested.

Disable-Device-Diagnostics-Intune-MEM-Admin-Center

**Comment by ktoliver** [comment]
@Yogesh-Shede Thank you. The update you submitted will merge in a new pull request in the public repo; we'll close this pull request. I'd look for the update to be live later today. Thanks.

**Pull request closed without merging**
