### PR TITLE
Update device-profile-create.md

### PR DESCRIPTION
**Pull request by msbemba**
Added permissions needed to create a device profile

Fixes https://github.com/MicrosoftDocs/memdocs/issues/3914

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — CHANGES_REQUESTED** [review]
Copy review.

**Comment by yogkumgit** [comment]
@MandiOhlinger Please review and signoff this PR. Thanks

**Comment by MandiOhlinger** [comment]
@msbemba We can't merge this PR. The roles you listed are too elevated for many organizations, and the roles you listed aren't the minimum role needed.

To see the roles that can create device configuration profiles, use the following steps.

1. In the Intune admin center, go to **Tenant administration** > **Roles**. 
2. Select a role > **Properties**. For example, select **Policy and Profile Manager** > **Properties**.
3. Scroll down to **Device configurations**. You can see this role has **Create** permissions.

They can do this for all the roles to determine which built-in rule has the **Create** permission for **Device configurations**.

I suggest sharing this info in the GitHub issue. I'm closing this PR w/o merging.

**Pull request closed without merging**
