### PR TITLE
Update quickstart-setup-hybrid-aad.md

### PR DESCRIPTION
**Pull request by hermanarnedo**
I didnt add the weblink to the blog post in my last change. Now it is updated! :-)

### CODE REVIEW

**Comment by PRMerger7** [comment]
@hermanarnedo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @hermanarnedo - This pull request was opened in the public repo. This content has a private repository, and PMs usually work in the private repo, per the Microsoft Docs contributor guide. We can keep this PR open for review and merge, but would you make future content updates in the private repo? Thank you!

**Comment by hermanarnedo** [comment]
@ktoliver  I will do! Thanks!

**Comment by PRMerger20** [comment]
@aczechowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by aczechowski — APPROVED** [review]
👍

**Comment by aczechowski** [comment]
#sign-off

**Pull request merged**
