### PR TITLE
IMEI numbers is not supported now.

### PR DESCRIPTION
**Pull request by 38cat**
IMEI numbers is not supported now.
There is a contradiction.
IMEI numbers is not supported in below table.
https://docs.microsoft.com/en-us/mem/intune/enrollment/corporate-identifiers-add#identify-corporate-owned-devices-with-imei-or-serial-number

image

### CODE REVIEW

**Comment by PRMerger9** [comment]
@38cat : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ErikjeMS** [comment]
@38cat I updated the table with corrected information yesterday. Can you review it again? It seems this will negate the need for your PR. Do you agree?

**Comment by 38cat** [comment]
@ErikjeMS Thank you for your update. I confirmed new table. I agree this, But only iOS written. Do not Android need this?

**Comment by ErikjeMS** [comment]
@38cat The Android information was updated. What exactly do you think needs to be added?

**Comment by 38cat** [comment]
@ErikjeMS Sorry, I'm very late reply. Thank you for your update.
Do you think don't need "See Important below." ? 
There are cases in Sometimes Android have multiple IMEI numbers.

If being you feel fussy, I'm sorry.

**Comment by ErikjeMS** [comment]
@38cat.

 @lenewsad is taking over this article. I'll let her decide whether or not your suggestion is needed Thanks!

**Comment by lenewsad** [comment]
#sign-off

**Comment by lenewsad** [comment]
There is a problem merging so  I'm closing this PR and resubmitting in another PR. Will run requested change by PM as the table appears to have changed since this contribution was made.

**Pull request closed without merging**
