### PR TITLE
Misleading description of the term "Offline". More distinction needs to be made to give the reader a better understanding of the term "Offline" with regards to Store for Business apps

### PR DESCRIPTION
**Pull request by byteben**
"Offline" apps can be regarded in two different contexts and I think a distinction needs to be made. Offline "Licensing" and Offline "Package deployment".
This article includes instructions for adding the Offline Company Portal app to Intune to distribute to Devices. The article context is for "Offline licensing". This means a valid license is not checked when the app is installed. This type of deployment is commonly, but not exclusively, used during Autopilot. During Autopilot, there is an increased chance of failure if, during the ESP, the device is required to check the Microsoft Store for Business for a valid license for an "Online" Store for Business app. Highlighting this would be beneficial to the reader.

The other context, which this article does not cover but the where the wording is misleading, is Offline "Package Deployment" for Store apps. This method requires an admin to download the offline package from the Store for Business to then distribute with Intune. This method is used if an admin wants to deploy a specific version of the Store app. Once the app is deployed it is then kept up-to-date as part of the normal application update cycle for all Store apps in Windows - it does not remain at the version deployed indefinitely - something the excerpt below could be seen to suggest":-

"Offline apps are managed by Intune, whereas online apps are managed by the store. Use offline apps when you need to install and maintain a specific app version".

Making a distinction between the two different contexts for "Offline" would clear up any confusion for deploying Store for Business apps with Intune.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@byteben : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@Erikre Could you review the proposed issue description? Note that the PR can't be merged as-is; #hold-off

**Comment by ktoliver** [comment]
(To open an issue for content in the repository: https://github.com/MicrosoftDocs/memdocs/issues)

**Comment by PRMerger9** [comment]
@Erikre : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Erikre** [comment]
@byteben - Thanks for the feedback. I modified the text and I'm updating it now. Thanks

**Comment by Erikre** [comment]
#sign-off

**Pull request merged**
