### PR TITLE
Improve DA Global Pilot example

### PR DESCRIPTION
**Pull request by MrRoundRobin**
Hi,

in the Example for Global Pilots [here](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/deploy-pilot#example) the `All Windows 10 clients` collection is added to the Global Pilot. This completely destroys the intelligence for automatic pilot suggestion. I would suggest to do something like in this PR.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@MrRoundRobin : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @MrRoundRobin for the contribution. I'm checking with @iceorbital.

**Comment by PRMerger19** [comment]
@aczechowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by aczechowski — APPROVED** [review]
Thanks again @MrRoundRobin for the contribution. Based on feedback from @iceorbital, I made some broader revisions to this section.

**Comment by aczechowski** [comment]
#sign-off

**Pull request merged**
