### PR TITLE
Correct terminology to Allowed Sites

### PR DESCRIPTION
**Pull request by SteveBurkettNZ**
The correct name of Safari bookmark folder they get added to is Allowed Sites.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@SteveBurkettNZ : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by MandiOhlinger — APPROVED** [review]

**Comment by MandiOhlinger** [comment]
#sign-off

**Comment by MandiOhlinger** [comment]
@SteveBurkettNZ Thank you!

**Comment by MandiOhlinger** [comment]
Manually merging PR since it hasn't been merged after waiting 21 hours.

**Pull request merged**
