### PR TITLE
Update add-devices.md

### PR DESCRIPTION
**Pull request by VigneshMSCRM**
Order of deleting the autopilot devices mentioned was wrong.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@VigneshMSCRM : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by aczechowski — APPROVED** [review]
Thanks @VigneshMSCRM for changing this, and _thank you_ for your first contribution to memdocs! 🎉 This looks good to me. I'll approve on behalf of the author who is out of the office.

**Comment by aczechowski** [comment]
#label:"ready-to-merge"

**Pull request merged**
