### PR TITLE
Added AADJ VM support

### PR DESCRIPTION
**Pull request by Jushiah**

### CODE REVIEW

**Comment by PRMerger10** [comment]
@Jushiah : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jushiah** [comment]
Can we schedule this change to go live on 7/15? Thanks!

**Comment by Jushiah** [comment]
+Maggie

**Comment by ErikjeMS** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ErikjeMS** [comment]
@ktoliver I don't see this change in the [live article](https://docs.microsoft.com/en-us/mem/intune/fundamentals/azure-virtual-desktop-multi-session), but you merged it before the morning publish. Do you have any idea what could be wrong?

**Comment by ktoliver** [comment]
> @ktoliver I don't see this change in the [live article](https://docs.microsoft.com/en-us/mem/intune/fundamentals/azure-virtual-desktop-multi-session), but you merged it before the morning publish. Do you have any idea what could be wrong?

The GitHub email notification for your comment @ErikjeMS was just delivered to me at 5:11 AM today. I do see the update live now. 👍🏼

**Pull request merged**
