### PR TITLE
Update get-cloud-pc-audit-logs-using-powershell.md

### PR DESCRIPTION
**Pull request by abrahamp91**
Adding the command to "Get entire list of audit events, including the audit actor"

### CODE REVIEW

**Comment by PRMerger19** [comment]
@abrahamp91 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ErikjeMS** [comment]
#sign-off

**Review by ErikjeMS — APPROVED** [review]

**Comment by ErikjeMS** [comment]
#sign-off

**Comment by ErikjeMS** [comment]
#sign-off

**Pull request closed without merging**
