### PR TITLE
Update supported-operating-systems-for-clients-and-devices.md

### PR DESCRIPTION
**Pull request by PalikaSingh**
removed Windows 8.1 support as end date is 10 Jan 2023

### CODE REVIEW

**Comment by PalikaSingh** [comment]
#sign-off

**Comment by Banreet** [comment]
#sign-off

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by PalikaSingh** [comment]
Hi magic docs Team,



This PR is approved, and it is still not merged in main. Can you please check the same.



Regards

Palika
________________________________

**Comment by JohanFreelancer9** [comment]
@yogkumgit, can you please help to get this PR merged?

**Comment by rjagiewich** [comment]
@tiburd @PalikaSingh - Palika, because this PR is in the public repo, PubOps can't merge it. Tina Burden might be able to. Thanks! -Rebecca

**Comment by PalikaSingh** [comment]
Hi Palika,
I've mentioned @Tina Burden (AQUENT ***@***.***> in the PR since she handles PRs in the public repo.

Thanks! -Rebecca

**Comment by PalikaSingh** [comment]
Hello,

The PR is merged (to main). Because it was submitted via the public repo, it will sync with the private repo in a sync PR before it's published to live. The next scheduled publish to live is Monday around 10:30 AM Seattle time.

For future reference, we recommend that Microsoft employees submit PRs via private repos.

Thanks!

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Rebecca Agiewich (AQUENT LLC) ***@***.***>
Sent: Friday, January 27, 2023 2:05:21 PM
To: Palika Singh ***@***.***>; MicrosoftDocs/memdocs ***@***.***>; Magic DOCS Publishing Operations ***@***.***>; MicrosoftDocs/memdocs ***@***.***>; Tina Burden (AQUENT LLC) ***@***.***>
Cc: Mention ***@***.***>; Banreet Kaur ***@***.***>; Balasubramanian Delli ***@***.***>
Subject: RE: [MicrosoftDocs/memdocs] Update supported-operating-systems-for-clients-and-devices.md (PR #3509)


Hi Palika,

I’ve mentioned @Tina Burden (AQUENT ***@***.***> in the PR since she handles PRs in the public repo.



Thanks! -Rebecca

**Pull request merged**
