### PR TITLE
Update app-discovered-apps.md

### PR DESCRIPTION
**Pull request by justengraves**
The workload slider should only relate to devices that are co-managed (as far as I'm aware).  Hybrid AAD join is not required for co-management or any particular configuration management approach.  I think the rest of this Note also needs clarity around if the app inventory being able to be collected within Intune is a product of having the IME only, or if the app inventory collection distinctly requires the app management workload be shifted (it currently reads like the app management workload shift is only required as a means to obtain the IME).

### CODE REVIEW

**Comment by PRMerger15** [comment]
@justengraves : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Erikre** [comment]
Reviewing this change with Arnab.

**Comment by justengraves** [comment]
Thanks, @Erikre.  Now that you've pointed out that it should be also be adjusted to "client apps workload", I'd also note that the second sentence in the paragraph also references the "app management workload" and should be changed as well.

**Comment by Erikre** [comment]
@justengraves - Yes, that makes sense. Thanks for your help. Normally, I'd make these changes in your PR and then publish, but I'm unable to edit at the moment. I'm checking on this. If you are able to update your PR, here's the needed change (best to do this from edit mode to pick the full markdown):

Windows 10 co-managed devices, as shown in the [client apps](https://docs.microsoft.com/mem/configmgr/comanage/workloads#client-apps) workload in Configuration Manager, do not currently collect app inventory through the Intune Management Extension (IME) as per the above schedule. To mitigate this issue, the client app workload in Configuration Manager should be switched to Intune for the IME to be installed on the device (IME is required for Win32 inventory and PowerShell deployment).

**Comment by justengraves** [comment]
@erikre - I can't edit either.  It also says "from unknown repository", so I'm guessing I forked it up somehow.  I can make a new PR with the edit and link it here if that helps.

**Comment by ktoliver** [comment]
Hi @justengraves - I can't edit it, either. There's an ongoing effort to troubleshoot this issue, which pops up here and there in various repos, both public and private. I was asked to ask you, when you created the PR, do you recall choosing to make the PR uneditable by clearing the option to **Allow edits from maintainers**?

**Comment by justengraves** [comment]
Hi @ktoliver - Nope, I wouldn't have unchecked anything that was default checked.  I haven't done a PR before, so I'm sure I was doing my best just to follow the instructions.  To step through it (if memory serves), before I found the proper method I believe I created my own fork and edited there.  When I went to create the pull request, I realized my mistake.  After doing the PR correctly (by clicking edit on the master branch) and committing, I went back to clean up my unintentional fork.  I'm thinking in doing so, I maybe also deleted the repo for this PR as well.

**Comment by ktoliver** [comment]
Yes, a missing (deleted) branch or fork is how I usually translate "unknown repository." I'll pass on your comment to the troubleshooters. Thanks!

@rmca14

**Comment by Erikre** [comment]
@justengraves - Rather than having you create a new PR, I could make these doc changes now, if that works for you.

**Comment by justengraves** [comment]
@Erikre - For sure, as long as I'm still allowed to reference this substantial contribution on my next Connect.

**Comment by Erikre** [comment]
@justengraves - Thanks for the feedback. I'm making your suggested changes now and closing this PR. This update should be published later today. Thanks again.

**Pull request closed without merging**
