### PR TITLE
added Global Admin rights

### PR DESCRIPTION
**Pull request by beigor1337**

### CODE REVIEW

**Comment by ErikjeMS** [comment]
@lenewsad, this is an enrollment issue. Can you review this PR? Thanks!

**Comment by ErikjeMS** [comment]
@lenewsad I think this is in your area now, right?

**Review by lenewsad — APPROVED** [review]

**Comment by lenewsad** [comment]
Thanks for your contribution @beigor1337! 

#sign-off

**Comment by PRMerger14** [comment]
@lenewsad: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by lenewsad** [comment]
@dougeby or @ErikjeMS, could you please sign off on this article? I am not seen as the author of this since it is an include file. Thank you!

**Comment by ErikjeMS** [comment]
#sign-off

**Comment by lenewsad** [comment]
> #sign-off

Thank you for trying Erik. :) I emailed PR team.

**Comment by traya1** [comment]
@tiburd FYI

**Pull request merged**
