### PR TITLE
Update docs to match the real-world behavior

### PR DESCRIPTION
**Pull request by andreiztm**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@andreiztm : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by andreiztm** [comment]
Discussed internally with @DavGuy-MSFT and @arcarley. 
Matching commit in the corresponding Update CSP docs:
https://github.com/MicrosoftDocs/windows-docs-pr/pull/6074/commits/f15adac8ab06abaebd516a460283b7d867b88a06

**Comment by andreiztm** [comment]
Please ignore/cancel this as I got help from @mestew on how to submit the change directly to the private repo. Thanks @mestew  :D

**Comment by Brenduns** [comment]
Replaced by PR https://github.com/MicrosoftDocs/memdocs-pr/pull/6358.

**Pull request closed without merging**
