### PR TITLE
Update enrollment-method-capab.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the document with details about running PS scripts. Reference https://docs.microsoft.com/en-us/mem/intune/apps/intune-management-extension
BYOD and device enrolled in GPO are able to run script

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/memdocs/issues/2200

**Comment by PRMerger8** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by yogkumgit** [comment]
@lenewsad Please review and merge this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@lenewsad Please review and merge this PR. Thanks

**Review by lenewsad — COMMENTED** [review]
Hi @msbemba, the PR didn't generate a full preview of the changes. Attaching the screenshot of what I can see: I notice that there is an asterisk right before the "Check," while the last column shows an asterisk right after the "Check." Can you doublecheck that the formatting is what you intended? Then I'll approve/sign off. We can always correct it after publishing if it still comes out funky. Thanks a lot!

image

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@lenewsad Thank you for the checking. I do not see the asterisk right before the check(while previewing), In fact, I'm using the same format as other checkmarks. 

Thanks
Sri

**Comment by lenewsad** [comment]
Fixed conflict

#sign-off

**Pull request merged**
