### PR TITLE
Update steps for non-default restriction priority

### PR DESCRIPTION
**Pull request by Yogesh-Shede**
Hi , I think there are some steps that need to updated as below on Link. I hope this is fine from your side. let me know ?  

Link  > https://docs.microsoft.com/en-us/mem/intune/enrollment/enrollment-restrictions-set#change-enrollment-restriction-priority

Steps as below:
1. Sign in to the Microsoft Endpoint Manager admin center and select Devices > Enroll devices > Enrollment restrictions.
2. Select the restriction that you want to change priority Device type restrictions or Device limit restrictions.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@Yogesh-Shede : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by lenewsad** [comment]
Hi @Yogesh-Shede, I'm seeing a different experience for step 1 so I will check with the product team and confirm these steps. Thanks for your patience.

**Review by lenewsad — CHANGES_REQUESTED** [review]
I need to check w/product team to verify steps.

**Comment by PRMerger6** [comment]
@lenewsad : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by lenewsad — APPROVED** [review]

**Comment by lenewsad** [comment]
#sign-off

**Pull request merged**
