### PR TITLE
Update store-apps-windows.md

### PR DESCRIPTION
**Pull request by msbemba**
Added clarity on the URL requirement as it shows https://www.microsoft.com/en-us/p/azure-vpn-client/9np355qt2sqb#activetab=pivot:overviewtab, But the URL that needs to be used is  https://www.microsoft.com/en-us/p/azure-vpn-client/9np355qt2sqb without the #activetab=pivot:overviewtab

### CODE REVIEW

**Comment by msbemba** [comment]
issue#https://github.com/MicrosoftDocs/memdocs/issues/1693

**Comment by msbemba** [comment]
@JohanFreelancer9 please copy review

**Comment by PRMerger10** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Erikre Please review and merge this PR. Thanks

**Comment by PRMerger18** [comment]
@Erikre : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Erikre — APPROVED** [review]

**Comment by Erikre** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
