### PR TITLE
Update deployment-guide-platform-macos.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the link for Add Microsoft Edge to macOS devices using Microsoft Intune

Issue#https://github.com/MicrosoftDocs/memdocs/issues/2976

### CODE REVIEW

**Comment by PRMerger7** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@lenewsad Please review and signoff this PR. Thanks

**Comment by lenewsad** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
