### PR TITLE
Added clarification to version restrictions

### PR DESCRIPTION
**Pull request by rogersoMS**
@ErikjeMS & @dagerrit 
Amended the note regarding version restrictions to clarify that it applies only to iOS and Android (via Company Portal). Meaning that version restrictions CAN be leveraged without the Company Portal, for Windows.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@rogersoMS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ErikjeMS** [comment]
@dagerrit Can you confirm this change?

**Comment by ErikjeMS** [comment]
@dagerrit Can you validate these suggested changes?

**Comment by ErikjeMS** [comment]
#sign-off

**Pull request merged**
