### PR TITLE
Update advanced-threat-protection-manage-android.md

### PR DESCRIPTION
**Pull request by shthota77**

### CODE REVIEW

**Comment by PRMerger9** [comment]
@shthota77 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@Brenduns : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@Brenduns : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Brenduns** [comment]
#sign-off

**Pull request merged**
