### PR TITLE
Update microsoft-intune-app-linux.md

### PR DESCRIPTION
**Pull request by psinnathurai**
Removed $ sign for a better copy past experience

### CODE REVIEW

**Comment by psinnathurai** [comment]
@microsoft-github-policy-service agree

**Comment by yogkumgit** [comment]
@lenewsad Please review and signoff this PR. Thanks

**Review by lenewsad — APPROVED** [review]
Thanks for your contribution @psinnathurai.

**Comment by lenewsad** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
