### PR TITLE
Google Play apps to unmanaged devices

### PR DESCRIPTION
**Pull request by crosoriov**
It is not straight forward to link the latest changes introduced to **Device Enrollment setting** option introduced in Company Portal customization to the scenario of deploying apps to unmanaged devices. I added a couple of lines that might help understand how this feature works in this scenario. 
Based on customer feedback, they are not able to come to the conclusion that that **Device Enrollment setting** will help prevent users from enrolling their device unintentionally or be confused with notifications asking them to enroll their device when it is not the company's intention.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@crosoriov : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @crosoriov - This pull request was opened in the public repo. PMs should work in the private repo, per the contributor guide. In the future, would you make content updates in the private repo? Thanks!

**Comment by crosoriov** [comment]
Sure @ktoliver, apologies for the mistake. Thank you.

**Review by Erikre — APPROVED** [review]

**Comment by PRMerger6** [comment]
@Erikre : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Erikre** [comment]
@crosoriov - Thank you for the feedback and suggestions. This update should be published soon.

**Comment by Erikre** [comment]
#sign-off

**Comment by PRMerger7** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
