### PR TITLE
Update microsoft-tunnel-conditional-access.md

### PR DESCRIPTION
**Pull request by franciscopgomes**
Requesting an update to the doc as the Application Administrator role does not allow users to run New-AzureADServicePrincipal:

new-azureadserviceprincipal : Error occurred while executing NewServicePrincipal
Code: Authorization_RequestDenied
Message: Insufficient privileges to complete the operation.

I could only execute this with a Global Administrator.

+ Correcting all mentions of "service principle" to "service principal"

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@franciscopgomes : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Brenduns Any update.

**Comment by Brenduns** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
