### PR TITLE
Update enrollment-method-capab.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated ability to run PS scripts in GPO as it is available

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by PRMerger7** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/memdocs/issues/2102

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@lenewsad Gentle reminder, Please merge this PR. Thanks

**Review by lenewsad — COMMENTED** [review]
@msbemba Before I sign off, can you confirm that the asterisk is where it should be? Thank you!

image

**Comment by yogkumgit** [comment]
@msbemba

**Comment by msbemba** [comment]
@lenewsad I don't see an asterisk when I preview. There should be no asterisk and I'm not really sure why it is showing up.

Thanks
Sri

**Comment by lenewsad** [comment]
#sign-off

**Pull request merged**
