### PR TITLE
Update role-based-access-control.md

### PR DESCRIPTION
**Pull request by msbemba**
Changed values for report reader after testing.

@Smritib17 could you once check internally before merging this PR

Fixes https://github.com/MicrosoftDocs/memdocs/issues/3979

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Smritib17 Please review and signoff this PR. Thanks

**Comment by yogkumgit** [comment]
@Smritib17 Gentle reminder.

**Comment by Smritib17** [comment]
Verified internally and can be changed.

**Review by Smritib17 — APPROVED** [review]

**Comment by Smritib17** [comment]
#sign-off

**Pull request merged**
