### PR TITLE
Update create-updates-with-updates-publisher.md

### PR DESCRIPTION
**Pull request by DavClk**
Recently discovered SCUP has a 2 GB package limit for new updates  adding documentation here until this limit changes.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@DavClk : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mestew** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
