### PR TITLE
Update multi-factor-authentication.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the document by removing " don't select Require device to be marked as compliant" as  Require device to be marked as compliant control does not block Intune enrollment.
Reference document https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-policy-compliant-device

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by PRMerger14** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/memdocs/issues/2068

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@lenewsad Please review and merge this PR. Thanks

**Comment by yogkumgit** [comment]
@lenewsad Gentle reminder, Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
