### PR TITLE
Update remote-content-library.md

### PR DESCRIPTION
**Pull request by davehop**
Add note to prereq section that manage content library button will be greyed out if the DP role is present on the site server

### CODE REVIEW

**Comment by PRMerger13** [comment]
@davehop : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by aczechowski — APPROVED** [review]
Thanks @davehop for adding this, and THANK YOU for your first contribution to memdocs! 🎉 This looks great!
Fixes #2178

**Comment by aczechowski** [comment]
#sign-off

**Comment by PRMerger20** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
