### PR TITLE
Update device-images.md

### PR DESCRIPTION
**Pull request by christiaanbrinkhoff**
Windows 11 support changes.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@christiaanbrinkhoff : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by ErikjeMS** [comment]
#hold-off

**Comment by ErikjeMS** [comment]
These changes were moved this PR: https://github.com/MicrosoftDocs/memdocs-pr/pull/5687

**Pull request closed without merging**
