### PR TITLE
Added internet access requirements

### PR DESCRIPTION
**Pull request by jonasatgit**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@jonasatgit : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger4** [comment]
@aczechowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by aczechowski — APPROVED** [review]
Thanks @jonasatgit for the contribution! I made a tweak to the link, pointing to the section of the CMG article that includes the same information (it's literally an include file between the two). But a good idea to include this information at this point. 😄

**Comment by aczechowski** [comment]
#sign-off

**Pull request merged**
