### PR TITLE
Adding section on Used space vs full disk encryption

### PR DESCRIPTION
**Pull request by rogersoMS**
Based on testing results from Daisuke Takabe and Sanesh Vig, adding details regarding used space only vs full disk encryption, including multiple screenshots.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@rogersoMS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger4** [comment]
@rogersoMS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Brenduns** [comment]
#sign-off

**Comment by Brenduns** [comment]
Merging so we can get this published.

**Pull request merged**
