### PR TITLE
Update windows-store-for-business.md

### PR DESCRIPTION
**Pull request by adrianwells**
Add more details to the note regarding the refund (removal) app current behavior.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@adrianwells : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Erikre** [comment]
@adrianwells - Thanks for the feedback. I've modified the text and I'm continuing to look into additional details to add. Once I have more information, I'll make additional updates. However for now, I'm closing this GitHub doc issue.

**Comment by Erikre** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@Erikre : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Erikre** [comment]
I've researched more and found that the history shows much more than just six months of app history. Removing the additional text from this PR.

**Comment by Erikre** [comment]
#sign-off

**Comment by adrianwells** [comment]
@Erikre Hi. If I am reading the current version correctly (https://github.com/MicrosoftDocs/memdocs/pull/591/commits/03f6d9cd29b44104268e43d10c235df49805be1e) ? It seems to be written to indicate how long Microsoft Store for Business history is maintained. If so, this seems to overlook the gist of PR that one cannot remove an app after 6 months. Hoped this PR would inform others that there's a time limit to refunds (ideally with a time period value) when trying to remove apps from Intune (Microsoft Endpoint Manager). Wondering if this can be edited to include this point?

**Comment by ktoliver** [comment]
@erikre Should we merge the PR or do you want to review/respond to this comment from @adrianwells? 

> @Erikre Hi. If I am reading the current version correctly ([03f6d9c](https://github.com/MicrosoftDocs/memdocs/commit/03f6d9cd29b44104268e43d10c235df49805be1e)) ? It seems to be written to indicate how long Microsoft Store for Business history is maintained. If so, this seems to overlook the gist of PR that one cannot remove an app after 6 months. Hoped this PR would inform others that there's a time limit to refunds (ideally with a time period value) when trying to remove apps from Intune (Microsoft Endpoint Manager). Wondering if this can be edited to include this point?

**Comment by Erikre** [comment]
@adrianwells and @ktoliver - My order history spans a time frame well over a year. The order history page does mention that the "maximum date range is 6 months", however that is referring to the search box, specifically the "Order date" drop down box I believe. Possibly, if you have an app that was purchased more than six months ago and is not listed on the order history page, there's another way to refund the app which support could help with, or determine why your app isn't showing up in the list. For now, I don't believe any changes can be made to this text until I have more information. I have an email started on this and once I have more information, I'll update the related text in the Intune docs. For now, I'm going to close this PR since I don't have any changes that can currently be made. 

If you do wish to contact support, there are a couple of options available:

- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.

- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support.

- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

**Comment by adrianwells** [comment]
@Erikre, thank you for the reply. This PR was a result of the Microsoft support indicating that six months is the limit and to clarify this for others as it was indicated as a fact. However, it seems there are some differing experiences here based on your comment? Microsoft support indicate there was no way to currently refund an app that was purchased older than six months ago. (Glad to chat more offline about the Microsoft support request specifics).

**Pull request closed without merging**
