### PR TITLE
Note Hybrid Azure AD unsupported

### PR DESCRIPTION
**Pull request by CBrasga**

### CODE REVIEW

**Comment by PRMerger16** [comment]
@CBrasga : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ErikjeMS** [comment]
Investigating with PM...

**Comment by ErikjeMS** [comment]
@CBrasga This statement does not need to be a note.

**Comment by CBrasga** [comment]
> @CBrasga This statement does not need to be a note.

Curious what the reasoning is? Generally exceptions are Noted. And this is an exception to "Corporate-owned Windows devices". Ego?

**Comment by ErikjeMS** [comment]
We have studies that show people are ignoring Notes. Also, we try to avoid using notes except for very important things. An exception to supported platforms does not rise to this level.

**Comment by CBrasga** [comment]
> We have studies that show people are ignoring Notes. Also, we try to avoid using notes except for very important things. An exception to supported platforms does not rise to this level.

Seems inconsistent. This page uses Notes to call out unsupported platforms: https://docs.microsoft.com/en-us/mem/intune/remote-actions/teamviewer-support

**Comment by ErikjeMS** [comment]
Yes, it's inconsistent. Policies change over time and not all past uses of Notes (etc.) have been assessed for updating.

**Pull request closed without merging**
