### PR TITLE
Update list of stores

### PR DESCRIPTION
**Pull request by msft-jy**

### CODE REVIEW

**Comment by PRMerger8** [comment]
@msft-jy : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @msft-jy - This PR was created in the public repo. PMs should work in the private repo, per the Microsoft Docs contributor guide. We can leave this PR here for review, but in the future, would you make content updates in the private repo? Thanks!

**Comment by msft-jy** [comment]
Sorry how do I find the private repo?

**Comment by ktoliver** [comment]
@msft-jy I'll send you email that has the info. Thanks.

**Pull request closed without merging**
