### PR TITLE
Update overview.md

### PR DESCRIPTION
**Pull request by hermanarnedo**
I didnt add correctly the link to the blog post last time. Now it is updated! :-)

### CODE REVIEW

**Comment by PRMerger6** [comment]
@hermanarnedo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@aczechowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by aczechowski — APPROVED** [review]
Thanks @hermanarnedo

**Comment by aczechowski** [comment]
#sign-off

**Pull request merged**
