### PR TITLE
Update apps-deploy.md

### PR DESCRIPTION
**Pull request by ab-starr**

### CODE REVIEW

**Comment by PRMerger5** [comment]
@ab-starr : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by Erikre — APPROVED** [review]

**Comment by Erikre** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
