### PR TITLE
Page Improvement: Intune For Education

### PR DESCRIPTION
**Pull request by allusai**
On the Intune for Education page, I believe we can slightly improve two paragraphs. The first edit I would like to suggest is switching the order of "Intune" and "Intune For Education" in the intro paragraph, I think switching the order makes it more clear for users. The second edit I would like to suggest is specifically mentioning the "full Intune console" and "Intune for Education console" in the second paragraph. As a first-time user, I was slightly confused about what "full device management experience" meant until I did more research. Since we can manage Android devices by using the "full Intune console", I believe mentioning that here more clearly will help a lot of other users.

Thank you!

### CODE REVIEW

**Comment by PRMerger13** [comment]
@allusai : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by lenewsad** [comment]
Hi @allusai, thanks for your contribution. The 1st edit you suggested is fine with me.

The 2nd contribution is already covered--in different words--in the paragraph beneath it. It starts with "Intune for Education can be used by itself or in harmony with...."  So please remove that addition. 

I do hear that you have interested in learning more about the differences between the Intune and Intune for Education experience. I will share this feedback with the product team for future improvement. 

After you've made the changes, I'll sign off. Thanks!

**Comment by PRMerger14** [comment]
@allusai : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by allusai** [comment]
Hello @lenewsad ! Thank you, I have made the changes you requested!

**Comment by lenewsad** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
