### PR TITLE
Update endpoint-antimalware-policies.md

### PR DESCRIPTION
**Pull request by CarlosLopez-MS**
Added the information regarding scheduled scans triggered when the machine is idle to reflect the same under the MECM documentation and Group Policy

### CODE REVIEW

**Comment by PRMerger12** [comment]
@CarlosLopez-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@mestew for review

Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]
Copy review - this PR is quite old. I am not sure if it is still relevant.

**Comment by dougeby** [comment]
updated to use the same terminology that is used in endpoint protection docs. Merging.

**Pull request merged**
