### PR TITLE
Update certificates-scep-configure.md

### PR DESCRIPTION
**Pull request by byteben**
The Enterprise Administrator Role is required to configure the NDES Service

### CODE REVIEW

**Comment by PRMerger17** [comment]
@byteben : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@Brenduns : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Brenduns** [comment]
@Byteben  Thanks for this submission. I did edit the presentation to present the credentials before the action.     #sign-off

**Comment by ktoliver** [comment]
Hi @Brenduns - Is this asterisk stray and to be deleted or does it match a footnote or something else?

image

Thanks.

**Comment by PRMerger14** [comment]
@Brenduns : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Brenduns** [comment]
@ktoliver   Thanks for catching that. The asterisk should have been removed. I've just updated that.

**Pull request merged**
