### PR TITLE
Update device-sync.md

### PR DESCRIPTION
**Pull request by msbemba**
removed To see the status of the sync action, choose **Devices** > **Monitor** > **Device actions**. as it is no longer available

Fixes https://github.com/MicrosoftDocs/memdocs/issues/3768

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Smritib17 Please review and sign off this PR. Thanks

**Review by Smritib17 — APPROVED** [review]

**Comment by Smritib17** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
