### PR TITLE
Update supported-devices-browsers.md

### PR DESCRIPTION
**Pull request by tktracker**
Please update this doc to include the Supported Platforms listed in this doc: https://docs.microsoft.com/en-us/mem/intune/protect/mde-security-integration.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@tktracker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by ErikjeMS** [comment]
@Smritib17 Do you own this article now? If so, here's a PR for you to review.

**Review by Smritib17 — APPROVED** [review]

**Comment by PRMerger18** [comment]
@Smritib17 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@Smritib17 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Smritib17 — APPROVED** [review]

**Comment by Smritib17** [comment]
@sign-off

**Pull request merged**
