### PR TITLE
Update task-sequence-variables.md

### PR DESCRIPTION
**Pull request by gwblok**
added SMSTSWaitCcmexecOperationalTimeout

### CODE REVIEW

**Comment by PRMerger19** [comment]
@gwblok : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by aczechowski — APPROVED** [review]
Hi @gwblok, thanks for the contribution! I think it's unlikely a coincidence that @frankroj submitted a similar change at the same time. 🤔 😁 The two PRs are different enough that I don't have to choose. I'll accept this one today, and then once it merges through to our private repo (where Frank submitted his PR), then I'll edit and combine. Win-win!

**Comment by aczechowski** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by gwblok** [comment]
Thank you
Probably not a coincidence.
Had an issue today where that variable would have been helpful, had I known
about it.  I searched this page first then reached out to our Wells Fargo
CM TAM.  He replied with that nugget so I figured I should update the docs
for the next person. I'm sure our TAM probably looped in Rojas.

Have a great weekend

**Comment by frankroj** [comment]
TAM did loop me in and I was surprised that we didn’t have this variable documented. 😊


Frank Rojas
Sr. Support Escalation Engineer | Cloud & Infrastructure Solutions | Microsoft Endpoint Configuration Manager
Customer Services & Support | Microsoft Corporation
•(980) 776-7712; • frank.rojas@microsoft.com<mailto:frank.rojas@microsoft.com>
Working Hours: Mon-Fri 11am-8pm EST

**Pull request merged**
