### PR TITLE
Update oemconfig-zebra-android-devices.md

### PR DESCRIPTION
**Pull request by msft-jy**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@msft-jy : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MandiOhlinger** [comment]
@msft-jy Hey - Can you create this PR in the private repo? I have several updates to make. If I make them, the PR will automatically close w/o merging your changes.

**Comment by ktoliver** [comment]
Hi @MandiOhlinger Should we close this PR? Thanks.

**Comment by MandiOhlinger** [comment]
@ktoliver I'll take care of it. I'm making these changes in the private repo. Thanks for the follow-up.

**Comment by MandiOhlinger** [comment]
Closing PR. Created new PR new PR in private repo.

**Pull request closed without merging**
