### PR TITLE
[sabieler] added WDS multicast known issue

### PR DESCRIPTION
**Pull request by sabieler**
- multicast stops working after upgrading to ADK for Windows 11

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@sabieler : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@aczechowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by aczechowski — APPROVED** [review]
Thanks @sabieler, I made a couple of tweaks, mostly to the URLs to remove the locale. But otherwise looks good 😄

**Comment by aczechowski** [comment]
#sign-off

**Pull request merged**
