### PR TITLE
Update triggerschedule method with example 3

### PR DESCRIPTION
**Pull request by ChadSimmons**
Added Example 3: Trigger Software Update Scan cache deletion and scan via Command Prompt using WMIC

### CODE REVIEW

**Comment by PRMerger18** [comment]
@ChadSimmons : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by aczechowski — APPROVED** [review]
Thanks @ChadSimmons for the contribution!

**Comment by aczechowski** [comment]
#sign-off

**Pull request merged**
