### PR TITLE
Removal of supervised update software-updates-declarative-ios-macos.md

### PR DESCRIPTION
**Pull request by Andy43917876**
Removed the supervised description from the declarative part of this article, as it's false information. Supervised is not required for DDM software updates: https://x.com/IntuneSuppTeam/status/1727271674649677986?s=20

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by Smritib17** [comment]
#sign-off

**Review by Smritib17 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Comment by Smritib17** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
