### PR TITLE
Update vpp-apps-ios.md

### PR DESCRIPTION
**Pull request by TaniaLimaP**
Automatic app updates currently allows Yes/No (not On/Off)

### CODE REVIEW

**Comment by PRMerger9** [comment]
@TaniaLimaP : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by lenewsad — APPROVED** [review]

**Comment by lenewsad** [comment]
Thank you for catching that change @TaniaLimaP!

**Comment by lenewsad** [comment]
#sign-off

**Comment by PRMerger20** [comment]
@lenewsad: I'm sorry - only the author of this article, @Erikre, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by lenewsad** [comment]
@Erikre I confirmed that this change needs to be made--do you mind adding the sign off? Thank you!

**Comment by ktoliver** [comment]
Merging; thanks for the review, @lenewsad.

**Pull request merged**
