### PR TITLE
Update screen shot & "Save" step missing.

### PR DESCRIPTION
**Pull request by Yogesh-Shede**
Hi,  I have observed that "Save" steps is missing Configure synchronization. In general at last step we should Save this configuration isn't it ?

What is your thoughts on this link ? I have also added screenshot which might be helpful. 

Link > https://docs.microsoft.com/en-us/mem/intune/apps/windows-store-for-business#configure-synchronization

### CODE REVIEW

**Comment by PRMerger18** [comment]
@Yogesh-Shede : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @Yogesh-Shede. 

Thanks for contributing to the documentation. 

It's not possible to submit image files through the GitHub UI, but you can complete the [tool setup steps](https://docs.microsoft.com/contribute/get-started-setup-tools) that are detailed in the Microsoft Docs contributor guide and submit image files in a pull request that way. There's a small learning curve, but the tools give you more options when you create a pull request.

Thanks!

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by Yogesh-Shede** [comment]
Ok. What about last step to save configuration? 
Can you please check that also.

**Comment by Yogesh-Shede** [comment]
Hi,

I was asking if last step is missing i.e. about "Save" configuration ?

1.Sign in to the Microsoft Endpoint Manager admin center.
2.Select Tenant administration > Connectors and tokens > Microsoft Store for Business.
3.Click Enable.
4.If you haven't already done so, click the link to sign up for the Microsoft Store for Business and associate your account as detailed previously.
5.From the Language drop-down list, choose the language in which apps from the Microsoft Store for Business are displayed in the portal. Regardless of the language in which they are displayed, they are installed in the end user's language when available.
6.Click Sync to get the apps you've purchased from the Microsoft Store into Intune.
7.Click on Save

**Comment by ktoliver** [comment]
@Erikre Could you take a look? 

Thanks.

**Comment by ktoliver** [comment]
@Erikre for review

Thanks.

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Erikre cc @dougeby Kindly update. Thanks

**Comment by Erikre** [comment]
Although the added image looks good, it is saved in public location and MSfB is being deprecated. Closing this PR because the update is no longer necessary. Thanks

**Pull request closed without merging**
