### PR TITLE
Update apple-mdm-push-certificate-get.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes as the apple ID can be changed whenever needed by using the apple account. So it is the apple account that needs to remain the same.

Per Issue#https://github.com/MicrosoftDocs/memdocs/issues/3277

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@lenewsad Please review and sign off this PR. Thanks

**Review by beflamm — APPROVED** [review]

**Review by lenewsad — APPROVED** [review]

**Comment by lenewsad** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
