### PR TITLE
Updated URLs for Enrolling Windows and IT visibility

### PR DESCRIPTION
**Pull request by drewjanderson**
The URLs that these hyperlinks directed to have changed and end at a 404. I corrected the links the best that I could find.

These were not markdown links to other .md files but full URL like the others were.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@drewjanderson : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ErikjeMS** [comment]
@drewjanderson Please remove the en-us from the new paths you've added. Then it looks good!

**Comment by PRMerger9** [comment]
@drewjanderson : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by drewjanderson** [comment]
Good catch, I didn't realize I needed to pay attention to that, but now I know. Thanks @ErikjeMS

**Comment by ErikjeMS** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
