### PR TITLE
Update reports-export-graph-available-reports.md

### PR DESCRIPTION
**Pull request by msbemba**
Added the filter required for UserInstallStautsAggregateByApp as it works only with the applicationid filter

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by PRMerger4** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/memdocs/issues/1887

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Erikre Please review and merge this PR. Thanks

**Pull request merged**
