### PR TITLE
Update security-baselines.md

### PR DESCRIPTION
**Pull request by msbemba**
removed the compare baseline section as the button has been removed recently, not sure if there is another view to compare now. for now removing it to avoid ambiguity

fixes#https://github.com/MicrosoftDocs/memdocs/issues/3348

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Brenduns Please review and sign off this PR. Thanks

**Comment by Brenduns** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
