### PR TITLE
Added info to clarify the storage location

### PR DESCRIPTION
**Pull request by AdamGrossTX**
The default storage location for reports is the root of the report server. Reports aren't saved into the ConfigMgr_<SiteCode> folder or any subfolder within that folder, they won't appear in the console.

image

image

### CODE REVIEW

**Comment by PRMerger20** [comment]
@AdamGrossTX : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@AdamGrossTX : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @aczechowski - Could you review the proposed update to your article? Thanks.

**Review by aczechowski — APPROVED** [review]
Thanks @AdamGrossTX for the contribution! 😄 Looks good

**Comment by aczechowski** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
