### PR TITLE
Update windows-autopilot-hybrid.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the list with Forticlent VPN, could not test but we have a reference - https://deploymentshare.com/using-forticlient-vpn-with-hybrid-aad-logon-after-autopilot-process/

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/memdocs/issues/2183

**Comment by msbemba** [comment]
@JohanFreelancer9 Please  copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@dougeby Kindly help. Thanks

**Comment by dougeby** [comment]
Looks fine

**Pull request merged**
