### PR TITLE
Adding tip for renaming the connector

### PR DESCRIPTION
**Pull request by adrian-moore**
Many customers struggle to find the NDES server in their environment after a long time. As the portal does not reference the install server, I think this tip will help with this scenario

### CODE REVIEW

**Comment by PRMerger20** [comment]
@adrian-moore : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by Brenduns** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
