### PR TITLE
Update enrollment-restrictions-set.md

### PR DESCRIPTION
**Pull request by msbemba**
Fixed hyperlink.

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/memdocs/issues/3092

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by lenewsad** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
