### PR TITLE
Update certificates-scep-configure.md

### PR DESCRIPTION
**Pull request by 1mb4dr**
NDES service computer must be added =).

### CODE REVIEW

**Comment by PRMerger19** [comment]
@1mb4dr : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@1mb4dr : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Brenduns** [comment]
@1mb4dr  Unfortunately, the intent for this PR isn't clear. The Security tab allows for adding Groups or Users, and the NDES Service account needs access as do those accounts that will create the SCEP profiles. The Computer account has not been identified by the Intune dev team, nor to date though support issues or other avenues as something that should be assigned access.  Therefore, I'll close this PR without further action.  Should you have supporting details to share, please do and we can revisit this.

**Comment by 1mb4dr** [comment]
Thanks for taking time to review.Want to share this how to :https://techcommunity.microsoft.com/t5/intune-customer-success/support-tip-how-to-configure-ndes-for-scep-certificate/ba-p/455125 as  you can see at the step we wre talking about there a Computer account icon on that screenshot.another link http://everythingaboutintune.com/2020/07/ndes-and-scep-setup-for-intune-a-complete-guide/Also I've tested that. Thanks.

**Pull request closed without merging**
