### PR TITLE
Update wi-fi-settings-ios.md

### PR DESCRIPTION
**Pull request by JarrettRenshaw**
Requested by Announ Diallo in CSS ContentIdea https://dev.azure.com/contentidea/ContentIdea/_workitems/edit/122839

### CODE REVIEW

**Comment by PRMerger13** [comment]
@JarrettRenshaw : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @JarrettRenshaw - Would you make future content updates in the private repo? A small update like this one might auto-merge in the private repo. Thanks!

**Comment by PRMerger18** [comment]
@MandiOhlinger : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MandiOhlinger** [comment]
#sign-off

**Pull request merged**
