### PR TITLE
Update plan-cloud-management-gateway.md

### PR DESCRIPTION
**Pull request by dereklangMSFT**

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@dereklangMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
#label:"aq-pr-triaged"

**Comment by aczechowski** [comment]
Thanks @dereklangMSFT for the contribution! I didn't think global admin was required for when you create the CMG. Let me check with engineering. If you have more background info, please send my way.

**Comment by aczechowski** [comment]
#sign-off

**Pull request merged**
