### PR TITLE
add a note for Default restrictions

### PR DESCRIPTION
**Pull request by RaPasca**
add a note to let customer know the impact of disabling ios/macos platform in default profile.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@RaPasca : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ErikjeMS** [comment]
#hold-off
I spoke to the PM and he said this information is a given and doesn't really need to be specifically stated.

**Comment by RaPasca** [comment]
Hi Erik,

Thanks for reaching out to me. But I disagree with this statement. I already have at least one customer that did not see this as a given. We need to have this stated somewhere because I was not 100% sure this is the case. I had to do a test to be sure.
In his scenario he wanted to block mac enrollment for everybody else with the exception of his test account. So he blocked the enrollment in the default rule and created a custom rule to allow mac enrollment only for his account.

This is the reason I requested the documentation update. I am not sure that page is the best place to put it, for me it’s good any piece of documentation that will just mention that, a small note.

Best Regards,

Radu Pascal
SUPPORT ESCAL ENG EMEA
Office: +40 (31) 1330715
Radu.Pascal@microsoft.com<mailto:Radu.Pascal@microsoft.com>
9 AM - 6 PM
If you have any feedback about my work, please let either me or my manager Daniela Maria Ionita know at daniela.ionita@microsoft.com<mailto:daniela.ionita@microsoft.com>

**Comment by spshumwa** [comment]
Radu are you saying that in order to enroll an iOS DEP device, you also need to allow MacOS enrollment as well? Or are you saying that in order to enroll an iOS DEP device you need to allow only iOS enrollment, and separately, if you want to enroll a MacOS device, you need to allow MacOS enrollment?

**Comment by RaPasca** [comment]
Hi Spencer,

What I am saying is iOS and/or macOS devices, if you block enrollment in the default profile, you can’t enroll DEP devices even if you allow the enrollment in a separate custom enrollment restriction targeting specific users.
Custom enrollment restrictions have higher priority than the default enrollment restriction and in theory can work, but it doesn’t.

iOS and macOS have similar behavior, not dependent on each other. The only  requirement is to have a valid APN cert that they share.

Regards,

Radu Pascal
SUPPORT ESCAL ENG EMEA
Office: +40 (31) 1330715
Radu.Pascal@microsoft.com<mailto:Radu.Pascal@microsoft.com>
9 AM - 6 PM
If you have any feedback about my work, please let either me or my manager Daniela Maria Ionita know at daniela.ionita@microsoft.com<mailto:daniela.ionita@microsoft.com>

**Pull request closed without merging**
