### PR TITLE
Update enroll-device-linux.md

### PR DESCRIPTION
**Pull request by ilwu-microsoft**
Added a note that all Linux devices enrolled with Intune are considered to be corporate.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@lenewsad Please review and signoff this PR. Thanks

**Comment by lenewsad** [comment]
Hi @yogkumgit, getting clarification from PM on edit before signing off. CC @ilwu-microsoft

**Review by lenewsad — APPROVED** [review]

**Comment by lenewsad** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
