### PR TITLE
Update certificate-connector-overview.md

### PR DESCRIPTION
**Pull request by msbemba**
Fixed the date (Typo)

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/memdocs/issues/3222

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by JohanFreelancer9** [comment]
@msbemba - This issue has also been fixed in PR #3225, so I suggest you can close this one. Thanks.

**Comment by Brenduns** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
