### PR TITLE
Update vpp-apps-ios.md

### PR DESCRIPTION
**Pull request by tktracker**
Per discussion with engineering feature team (Jason Kraft), the sync with Apple for Vpp tokens happens once a day instead of twice a day.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@tktracker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by jakraft — APPROVED** [review]
LGTM

**Comment by Erikre** [comment]
#sign-off

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks.

**Pull request merged**
