### PR TITLE
Update scenario-health.md

### PR DESCRIPTION
**Pull request by Leicham**
removed duplicate language per #1777

### CODE REVIEW

**Comment by PRMerger17** [comment]
@Leicham : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by aczechowski — APPROVED** [review]
Thanks @Leicham for the contribution! 😄

**Comment by aczechowski** [comment]
#sign-off 

fixes #1777

**Comment by aczechowski** [comment]
#hold-off

**Comment by aczechowski** [comment]
I just realized that @jpcast88 already made this change in our private repo (MicrosoftDocs/memdocs-pr#4900). So this PR isn't needed now (and will likely cause a merge conflict if we tried to take it). Sorry! I look forward to seeing your next PR 😉

**Pull request closed without merging**
