### PR TITLE
Update actions-for-noncompliance.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to Retire the noncompliant device

Fixes https://github.com/MicrosoftDocs/memdocs/issues/4101

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by Brenduns** [comment]
@msbemba  I've lightly edited this pr, but am not able to do the full review needed at this time.

I do see four other references in this same article to the old text, ' _Retire the noncompliant device_ ' that will also need to be updated to the new text version, with the surrounding text reviewed to apply updates if necessary to align to the described behavior of adding the device to a list for retirment, vs actually triggering retirment.  

Those will need to be fixed before we can publish this PR, as the mix of references could be seen as more confusing than the simple change of teh direct command/option references.

**Comment by Brenduns** [comment]
#hold-off

Publishing is pending additional edits in the same article to align to the updated UI option for retiring devices.

**Comment by yogkumgit** [comment]
@Brenduns Please review. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by Brenduns** [comment]
@yogkumgit   @msbemba    There remain four additional references to  **Retire the noncompliant device** that require updates in this PR before this can be accepted. Please fix them as well.

**Comment by yogkumgit** [comment]
@msbemba Please update.

**Comment by msbemba** [comment]
@Brenduns Thank you. I have made the changes.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by Brenduns** [comment]
Fixing merge conflict.
#sign-off

**Pull request merged**
