### PR TITLE
Page Improvement: What Is Device Management

### PR DESCRIPTION
**Pull request by allusai**
I would like to suggest an improvement to the "What Is Device Management Page". I feel like the original description did a great job of explaining device management and a situation where Administrators can use Microsoft Intune (protecting data on devices that are being used by users for personal reasons too). But I feel like my description highlights those topics in a more clear way. I think by rewriting the introduction paragraph like this, it will help demonstrate the value of Intune to Administrators more and make them more likely to adopt Intune as an MDM solution for their organization. The last sentence I added in my new version felt especially important for me because it really highlights the task at hand for the administrator: making it easy for users to access the organization's information with any device but protecting the company’s data at the same time.

Thank you!

### CODE REVIEW

**Comment by PRMerger9** [comment]
@allusai : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@MandiOhlinger : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MandiOhlinger** [comment]
@allusai You're on a roll. Thank you!

#sign-off

**Comment by allusai** [comment]
Thank you Mandi!

**Pull request merged**
