### PR TITLE
Update collect-diagnostics.md

### PR DESCRIPTION
**Pull request by mackie1604**
updating 12 hour window to 24 hour window.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@mackie1604 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mackie1604** [comment]
#sign-off.

**Comment by PRMerger8** [comment]
@mackie1604: I'm sorry - only the author of this article, @ErikjeMS, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ErikjeMS** [comment]
#sign-off

**Pull request merged**
