### PR TITLE
Update quickstart-setup-auto-enrollment.md

### PR DESCRIPTION
**Pull request by msbemba**
removed Choose **Select groups** > **Contoso Testers** > **Select** as the assigned group for MAM as we are chossing None in user scope

Fixes https://github.com/MicrosoftDocs/memdocs/issues/3860

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by lenewsad** [comment]
Hi @msbemba, thank you for making the change. I'm pinging the PM to confirm.

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by lenewsad — APPROVED** [review]

**Comment by lenewsad** [comment]
#sign-off

**Comment by lenewsad** [comment]
PM approved--thanks @msbemba.

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@tiburd Gentle reminder

**Comment by lenewsad** [comment]
Hi @msbemba @tiburd, I resolved the conflicts. It is ready to be merged now. Thank  you!

**Comment by lenewsad** [comment]
#sign-off

**Pull request merged**
