### PR TITLE
Update certificate-connector-install.md

### PR DESCRIPTION
**Pull request by ertansimsek**
The user who is performing the login to Azure with the certificate connector must be a synchronized user from the local/on-premises AD

### CODE REVIEW

**Comment by PRMerger8** [comment]
@ertansimsek : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by Brenduns** [comment]
#sign-off        @ertansimsek  Thanks for this PR submission (I've been out or I'd have accepted it sooner).

**Comment by Brenduns** [comment]
#sign-off

**Pull request merged**
