### PR TITLE
Update screenshot and "Scripts" section

### PR DESCRIPTION
**Pull request by Yogesh-Shede**
Hi,
Please update screenshot and Scripts section for Windows 10. 
This is now showing as  Select **Devices** > **Scripts** > **Add** > **Windows 10** in Intune console.

Link > https://docs.microsoft.com/en-us/mem/intune/apps/intune-management-extension#create-a-script-policy-and-assign-it

### CODE REVIEW

**Comment by PRMerger12** [comment]
@Yogesh-Shede : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @Yogesh-Shede - I believe that you can't submit image files when you edit an article in the GitHub UI, but you can add an image file to your pull request if you make the updates by using [content authoring tools](https://docs.microsoft.com/contribute/get-started-setup-tools). If you plan to submit new image files regularly, you might go ahead and get set up to do that; it will be more streamlined. We can't merge PRs that contain only links to images that are hosted elsewhere. Thanks!

**Comment by Yogesh-Shede** [comment]
Hi Kristine,

Thanks for your feedback.

I have to understand how to update by using content authorising tools.

If required I may contact you. I hope this is fine with you?

Regards,
Yogesh Shede.

**Review by Erikre — APPROVED** [review]

**Comment by Erikre** [comment]
@Yogesh-Shede - Thank you for your contribution. We're publishing this change now.

**Comment by ktoliver** [comment]
The PR review team will move the commit to the private repo, so we can create an image file from the included screenshot. We'll post here at that point. Thanks.

**Comment by ktoliver** [comment]
We'll merge the update from a new pull request in the private repository, so we'll close this PR now. Thanks!

**Pull request closed without merging**
