### PR TITLE
App groups cannot be used in TS

### PR DESCRIPTION
**Pull request by PanuSaukko**
I added a new known issue that you can use application groups with Install Application task sequence step.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@PanuSaukko : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by aczechowski — APPROVED** [review]
Thanks @PanuSaukko 😄

**Comment by aczechowski** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
