### PR TITLE
Update updates.md

### PR DESCRIPTION
**Pull request by dereklangMSFT**
Added 2103 to historical versions list

### CODE REVIEW

**Comment by traya1** [comment]
Learn Build status updates of commit _[c5964fb](https://github.com/dereklangMSFT/memdocs/commits/c5964fb26f113a572c12f071607e8422ec4a30b8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[memdocs/configmgr/core/servers/manage/updates.md](https://github.com/dereklangMSFT/memdocs/blob/patch-6/memdocs/configmgr/core/servers/manage/updates.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/aa268e4d-aaaf-30c8-4118-35d62ca794c9/202212101749417929-3440/BuildReport?accessString=cf94657f36190b7cab77a0202f9ab6d7ca4c5f9aacfa310cb7adea831bd83350).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/aa268e4d-aaaf-30c8-4118-35d62ca794c9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by gowdhamankarthikeyan — APPROVED** [review]

**Comment by gowdhamankarthikeyan** [comment]
#sign-off

**Review by gowdhamankarthikeyan — APPROVED** [review]
#sign-off

**Review by gowdhamankarthikeyan — APPROVED** [review]
Approved

**Comment by gowdhamankarthikeyan** [comment]
#sign-off

**Comment by dougeby** [comment]
This info is outdated and the article is updated with new info. Closing PR

**Pull request closed without merging**
