### PR TITLE
Update what-is-intune.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the Azure link as it is directed to Portal.azure.com and this has been moved to https://endpoint.microsoft.com

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by PRMerger9** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/memdocs/issues/2113

**Comment by yogkumgit** [comment]
@dougeby Please review and merge this PR. Thanks

**Comment by yogkumgit** [comment]
@dougeby Gentle reminder, Please merge this PR. Thanks

**Comment by PRMerger15** [comment]
@dougeby : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@dougeby : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by dougeby** [comment]
I removed the ways to get Intune and changed to the licensing article because the steps were outdated.

**Pull request merged**
