### PR TITLE
Adding information for ValuesToScrubFromLogging

### PR DESCRIPTION
**Pull request by hhawkins**
App developers can now add a list of app config values that they'd like to have scrubbed from the logs. This documentation update to the "Configure settings for the Intune App SDK" section at the bottom of the list will let users know how to do this.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@hhawkins : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by ktoliver** [comment]
@Erikre for review

Thanks.

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Erikre cc @dougeby Kindly update. Thanks

**Review by Erikre — APPROVED** [review]

**Comment by Erikre** [comment]
#sign-off

**Pull request merged**
