### PR TITLE
Removing ADAL

### PR DESCRIPTION
**Pull request by rwike77**
ADAL is being deprecated in June:  https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-migration .  Cleaning up content before the deprecation.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@rwike77 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
#label:"aq-pr-triaged"

**Review by aczechowski — APPROVED** [review]
Thanks @rwike77 for the contribution! This change is very similar to that in #2310 which @Brenduns approved, so I think we can easily do the same here. I'll approve on Doug's behalf
#label:"ready-to-merge"

**Comment by aczechowski** [comment]
#label:"ready-to-merge"

**Pull request merged**
