### PR TITLE
Update lob-apps-macos-dmg.md

### PR DESCRIPTION
**Pull request by mnahum**
fix a copy/Past error for next step

### CODE REVIEW

**Comment by PRMerger8** [comment]
@mnahum : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@mnahum : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Erikre — APPROVED** [review]

**Comment by Erikre** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Comment by PRMerger5** [comment]
@tiburd : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
