### PR TITLE
Update identity-protection-configure.md

### PR DESCRIPTION
**Pull request by saurabhkoshta**
Change as per: https://portal.microsofticm.com/imp/v3/incidents/details/213191310/home

### CODE REVIEW

**Comment by PRMerger15** [comment]
@saurabhkoshta : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by matt-call** [comment]
Discussed with team - There seems to be some mix up. Even though this setting will always apply to the **User** scope, it can be applied to device groups as well as user groups - @Brenduns - I think this change should be prevented from merging and Intune PM does not approve this change.

**Comment by ktoliver** [comment]
#hold-off

**Comment by Brenduns** [comment]
Based on Matts feedback, I'm closing this PR.  Email conversations are underway to determine what the underlying details for content would be.

**Pull request closed without merging**
