### PR TITLE
Update mam-faq.yml

### PR DESCRIPTION
**Pull request by msbemba**
Made correction to the doc as it currently states app types instead of device types

### CODE REVIEW

**Comment by PRMerger15** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
issue#https://github.com/MicrosoftDocs/memdocs/issues/1931

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Erikre Please review and merge this PR. Thanks

**Comment by yogkumgit** [comment]
@Erikre Gentle reminder. Thanks

**Pull request merged**
