### PR TITLE
Updated to use endpoint.microsoft.com

### PR DESCRIPTION
**Pull request by AdamGrossTX**
Since the Intune portal in Azure will soon be replaced with endpoint.microsoft.com, I thought this should point there instead.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@AdamGrossTX : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@mestew : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@mestew : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mestew** [comment]
#sign-off @AdamGrossTX thanks so much!

**Pull request merged**
