### PR TITLE
Update apps-add-office365.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated title to reflect Microsoft 365 Apps instead of apps

Per issue#https://github.com/MicrosoftDocs/memdocs/issues/2973

### CODE REVIEW

**Comment by PRMerger4** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Erikre Please review and sign off this PR. Thanks

**Comment by yogkumgit** [comment]
@Erikre Gentle reminder

**Review by Erikre — APPROVED** [review]

**Comment by Erikre** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
