### PR TITLE
Add recently created accounts default setting

### PR DESCRIPTION
**Pull request by sufuruka**
Please add following notes in the docs.

This "Unlicensed admins" option has been enabled by default on all accounts created after 2006 release.

I confirmed that created account tenant in recently is this option has been enabled by default.
This option setting changed on 2006 release. Before 2006 release tenant users are able to be enabled in manually.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@sufuruka : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ErikjeMS** [comment]
Investigating with PM...

**Comment by ErikjeMS** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
