### PR TITLE
Update ios-ipados-supervised-device-security-configurations.md

### PR DESCRIPTION
**Pull request by msbemba**
removed block dicatation for Siri as it seems to be bug in Aplpe and it does not work.

MSFT ticket2306210010001319

Fixes https://github.com/MicrosoftDocs/memdocs/issues/4097

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@lenewsad Please review and signoff this PR. Thanks

**Review by lenewsad — APPROVED** [review]

**Comment by lenewsad** [comment]
Thank you @msbemba, I confirmed that this setting should be removed.

**Comment by lenewsad** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
