### PR TITLE
Changed Windows 10 RS5 to 1809

### PR DESCRIPTION
**Pull request by PanuSaukko**
Please, never use Microsoft internal Windows 10 codenames like RS5 in public doc articles. Nobody in outside world remembers them.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@PanuSaukko : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by ErikjeMS — CHANGES_REQUESTED** [review]
Hi, @PanuSaukko, We use the following term in our docs: "Windows 10 RS5 (1809) and newer". Can you change your PR to that? Thanks!

**Comment by PRMerger6** [comment]
@ErikjeMS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@ErikjeMS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ErikjeMS** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
