### PR TITLE
Adding information about iOS User enrollment

### PR DESCRIPTION
**Pull request by yushinok**
I am adding Notes to explain the combination of iOS user enrollment profile and Blocking personal device enrollment restrictions.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@yushinok : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @yushinok - This pull request was opened in the public repo. The content has a private repository, and PMs usually work in the private repo, per the Microsoft Docs contributor guide. We can keep this PR open for review and merge, but would you make future content updates in the private repo? Thank you!

**Comment by ktoliver** [comment]
@ErikjeMS - Could you review the proposed update to your article? If you approve the update, I could edit it to something like this (if my revisions are accurate--_overrides all enrollment restriction policies_?):

`> [!NOTE]`
`> An iOS User Enrollment profile overrides an enrollment restriction policy. For more information, see [Set up iOS/iPadOS and iPadOS User Enrollment (preview)](ios-user-enrollment.md).`
`>`

**Comment by ErikjeMS** [comment]
@ktoliver Your changes look good. #sign-off

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Thanks @ErikjeMS. I made the revision and will merge.

**Comment by yushinok** [comment]
@ktoliver  
I am sorry for opening PR not in private repo. 
I will make future content updates in the private repo.

**Pull request merged**
