### PR TITLE
Update apps-supported-intune-apps.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated app pretection for  Lists on Android and Lens on Android and iOS support support 

 Neither are listed on this page:
https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-grant#require-approved-client-app

After configuring in my app protection policies  neither app picks up the policy and lens does not ever request a log in.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by yogkumgit** [comment]
@Erikre Please review and Signoff this PR. Thanks

**Comment by Erikre** [comment]
#sign-off

**Pull request merged**
