### PR TITLE
Update windows-bulk-enroll.md

### PR DESCRIPTION
**Pull request by byteben**
Conditional Access exception not noted.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@byteben : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ErikjeMS** [comment]
Investigating with PM...

**Comment by byteben** [comment]
If it helps, the following doc refers to the exception https://docs.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-manager-enroll

**Comment by ErikjeMS** [comment]
@byteben Yep, that helps! Thanks!

**Comment by ErikjeMS** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
