### PR TITLE
Corrected 8Gb -> 8GB in image.

### LINKED ISSUE #1168: Please write clearly bit or Byte
In the picture of process flow, it is written as "Is less than 8Gb". Is this "8Gb" means 8 Giga bit? (I think "b" means bit, "B" means Byte.) Is this correct?
It will be good to write clearly.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7383079e-6f37-0a16-dc33-dee91f345856
* Version Independent ID: bda30218-6596-90ef-b75d-4a983b9e949b
* Content: [Prepare a Win32 app to be uploaded to Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/apps/apps-win32-prepare)
* Content Source: [memdocs/intune/apps/apps-win32-prepare.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/apps/apps-win32-prepare.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

### PR DESCRIPTION
**Pull request by ChrisKibble**
Fixes #1168

### CODE REVIEW

**Comment by Erikre** [comment]
@ChrisKibble - Thanks for the feedback and contribution. Looks good.

**Comment by Erikre** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@Erikre: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by Erikre — APPROVED** [review]

**Comment by Erikre** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@Erikre: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
