### PR TITLE
Update microsoft-tunnel-configure.md

### PR DESCRIPTION
**Pull request by yangsa666**
PR Summary:
Change: Correct AutoOnboard to SilentOnboard
Reason: MDE for iOS doesn't recognize AutoOnboard pararm, it doesn't work. By our tests, it should use SilentOnboard instead.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yangsa666** [comment]
Hi @Brenduns , would you like to take a review on this PR? Thanks.

**Comment by Brenduns** [comment]
@yangsa666  I regret that this is still pending. I forwarded this PR to our product group team On July 5th for guidance, but  they haven't yet completed their evaluation of the two settings and what should, or might not be working as expected.  Once I am provided with details, I'll be able to update you via this communication channel and act on this PR.

**Comment by yogkumgit** [comment]
@Brenduns Please update. Thanks

**Comment by Brenduns** [comment]
The product group and devs have bounced this around in discussion and testing, but the last word has been (for some time now), that SilentOnboard didn’t work as was expected for Tunnel. 

At this time with no change of stance from Dev, I'll close this content PR.

**Pull request closed without merging**
