### PR TITLE
Update server-auth-cert.md

### PR DESCRIPTION
**Pull request by JordanTheITGuy**
Just adding an IMPORTANT - not one the DNS prefix - section. 

I've had a few customers miss this and then they just create a certificate in the next step... they miss it and then have to cancel and re-issue the public cert. 

Would be nice to ensure they have a little more visibility on this critical step.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@JordanTheITGuy : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@aczechowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by aczechowski — APPROVED** [review]
Thanks @JordanTheITGuy, that makes sense. Good call. I made one small tweak for syntax

**Comment by aczechowski** [comment]
#sign-off

**Pull request merged**
