### PR TITLE
Update windows-update-for-business-configure.md

### PR DESCRIPTION
**Pull request by v-rechau**
Adding a warning about MSA blocking Feature Updates.

This definitely needed more visibility as the interaction between that setting and WUfB is not intuitive. When troubleshooting why their managed devices aren't receiving new feature updates, admins are much more likely to believe the update policies aren't being deployed properly.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@v-rechau : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Brenduns** [comment]
@v-rechau   This is a great note to add to Intune docs and not something that's been raised before. However, this location isn't the best spot to add that as this is the introductory section for updates in general. Instead, per my read of the issue in the Windows article, this appears to be specific to Feature updates which makes this a better fit as a prerequisite under the *Devices must* bullet point as found in **windows-10-feature-updates.md**, our article dedicated to using [Feature Updates](https://docs.microsoft.com/mem/intune/protect/windows-10-feature-updates).

If you'd like credit for the contribution, please shift this note to be a new prerequisite in that article (it doesn't need to be in Note form in that case), but do include the link to the troubleshooting article.  

On Wednesday, I'll go ahead and add that myself if you've not been able to respond or take that action.

**Comment by v-rechau** [comment]
@Brenduns Thanks for the insights. I thought about placing it there, but the Features Policy is mostly targeted at updating a machine to a specific level and "freezing" it there, while Update Rings lets admins configure the Feature Updates to be running and expect them to get feature updates as they come.

Since it affected both, I figured the intro section would be a good neutral place for it. If you would prefer for it to be moved to the Prerequisites section of both of those pages, I'll commit the changes tonight.

**Comment by Brenduns** [comment]
@v-rechau  Both locations sounds good.  That way it won't be missed. Thank you.

**Comment by PRMerger10** [comment]
@FireSiku : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@v-rechau : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Brenduns** [comment]
#sign-off

**Comment by PRMerger20** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
