### PR TITLE
Update conditional-access-exchange-create.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the document to reduce ambiguity

closes #https://github.com/MicrosoftDocs/memdocs/issues/3346

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — CHANGES_REQUESTED** [review]
Copy review.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Brenduns Please review and sign off this PR. Thanks

**Comment by Brenduns** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
