### PR TITLE
update working for unsupported scenario DEM + ADE

### PR DESCRIPTION
**Pull request by CarHern**
Updating wording to avoid confusion as "DEM accounts cannot be used when enrolling devices via Apple's Automated Device Enrollment (ADE)." is miss leading for customers as the fact is that you CAN use an account (you will face issues and get unexpected behaviors because again this is not SUPPORTED) but you can Technically add/use the account because there is nothing from the service that Stops or prevents you from doing it.

look at this ICM with Intune Engineering https://portal.microsofticm.com/imp/v3/incidents/details/277021235/home

### CODE REVIEW

**Comment by PRMerger15** [comment]
@CarHern : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by PRMerger10** [comment]
@lenewsad : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@lenewsad : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by lenewsad** [comment]
Thanks for your contribution @CarHern!

#sign-off

**Pull request merged**
