### PR TITLE
Update vpp-apps-ios.md

### PR DESCRIPTION
**Pull request by andrew-s-taylor**
The location of the VPP token has moved within Apple Business Manager.  New location updated

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Erikre Please review and signoff this PR. Thanks

**Comment by yogkumgit** [comment]
@Erikre Gentle reminder.

**Review by Erikre — APPROVED** [review]

**Comment by Erikre** [comment]
#sign-off

**Review by Erikre — APPROVED** [review]

**Comment by Erikre** [comment]
#sign-off

**Pull request merged**
