### PR TITLE
Update reports-export-graph-available-reports.md

### PR DESCRIPTION
**Pull request by AdamGrossTX**
Removed extra PolicyId reference.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Erikre Please review and sign off this Pr. Thanks

**Comment by yogkumgit** [comment]
@Erikre Gentle reminder.

**Review by Erikre — APPROVED** [review]

**Comment by Erikre** [comment]
#sign-off

**Comment by Erikre** [comment]
#sign-off

**Pull request merged**
