### PR TITLE
Update app-configuration-managed-home-screen-app.md

### PR DESCRIPTION
**Pull request by chmaguir**

### CODE REVIEW

**Comment by PRMerger8** [comment]
@chmaguir : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@Erikre : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@Erikre : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Erikre** [comment]
#sign-off

**Review by Erikre — APPROVED** [review]

**Comment by Erikre** [comment]
#sign-off

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
