### PR TITLE
Update licenses.md

### PR DESCRIPTION
**Pull request by msbemba**
Added Microsoft Teams Rooms Standard and Microsoft Teams Rooms Premium as they include Microsoft intune license. Reference - https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-licensing#licensing-solutions-for-shared-communication-devices

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/memdocs/issues/2693

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Erikre Please review and SignOff this PR. Thanks

**Comment by yogkumgit** [comment]
@Erikre

**Comment by yogkumgit** [comment]
@Erikre Gentle reminder

**Comment by Erikre** [comment]
I don't believe this update should be included. I couldn't confirm Teams Rooms includes Intune listed as part of the [licensing docs](https://www.microsoft.com/en-us/microsoft-teams/microsoft-teams-rooms/compare-rooms-plans#office-ContentAreaHeadingTemplate-isehs87).

**Pull request closed without merging**
