### PR TITLE
Update custom-notifications.md

### PR DESCRIPTION
**Pull request by fabiobaleizao**
Good morning,

I stepped onto a case where customer is saying that he cannot send a custom notification for a specific device.
After analyzing the case, I saw he was trying to send a custom notification for an Android Corporate owned device type.
After looking into my tenant, I realized we cannot send custom notifications for this kind of enrollment.
For instance, if you have a Fully managed device or corporate owned device, you cannot send a custom notification.
This only works for BYOD enrollment type.
However, this is not specified in our public article.

Could you update the article to have this specification mentioned?

You can get in touch with me if you need further details.
Thank you in advance.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@fabiobaleizao : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@Brenduns Could you review the proposed update? The repo's quality criteria requires images that are referenced from an MD file to be in the repo; we can't link to images that are hosted elsewhere. If the update is approved, the PR review team can help create image files from screenshots after moving the commit to the private repo, if needed. Let us know. Thanks.

**Comment by Brenduns** [comment]
Still pending PM feedback on the details before we can fix up the PR.

**Comment by Brenduns** [comment]
Closing this PR for now.  We'll need product group feedback to proceed.

**Pull request closed without merging**
