### PR TITLE
Update apple-mdm-push-certificate-get.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the file name for CSR 

The CSR File needs to be renamed as IntuneCSR.csr.txt.

Fixes https://github.com/MicrosoftDocs/memdocs/issues/4434

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — CHANGES_REQUESTED** [review]
Copy review.

**Comment by yogkumgit** [comment]
@msbemba

**Comment by yogkumgit** [comment]
@lenewsad Please review and sign off this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by lenewsad** [comment]
Hi @msbemba, I'm checking with the product team on this, thank you.

**Comment by lenewsad** [comment]
Hi @msbemba, I tried to reproduce this issue, but the CSR file uploaded as iexpected on my end. Since the error is happening in the Apple Push Certificates Portal, we recommend reaching out to [Apple Support](https://support.apple.com/en-us/HT208643) to find out why the file isn't uploading as expected.

**Pull request closed without merging**
