### PR TITLE
Update considerations-for-managing-clients-in-a-vdi.md

### PR DESCRIPTION
**Pull request by AdamGrossTX**
Adding Non-Persistent verbiage for clarity

### CODE REVIEW

**Comment by PRMerger6** [comment]
@AdamGrossTX : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@AdamGrossTX : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by aczechowski — APPROVED** [review]
Thanks @AdamGrossTX 😄 good addition. And thank you, as always, for making the quick contribution!

I double-checked for any internal links to that header (anchor #pooled-vms) and didn't find any, so no issues with changing the header title.

**Comment by aczechowski** [comment]
#sign-off

**Comment by ktoliver** [comment]
Wondering if "pooled/nonpersistent VMs" might be accurate for a follow-up PR (if not, disregard and carry on). Merging now. Thanks.

**Comment by aczechowski** [comment]
@ktoliver good catch! I always forget about that style guideline. Style Guide has the following on the topic:

- https://docs.microsoft.com/en-us/style-guide/punctuation/dashes-hyphens/hyphens#prefixes
- https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/n/non

"Non-persistent" isn't in AHD, but "nonpersistent" is: https://ahdictionary.com/word/search.html?q=nonpersistent

@AdamGrossTX you want another quick edit? 😉 If not, no worries, I can clean it up. 

(Realistically, because of the age of many of these articles, they don't always follow the latest style recommendations. There are currently 837 instances across 562 files in just memdocs/configmgr for "non-" 😮  Other than instances where we explicitly want to stay internally consistent [like co-management], we should try to follow current style for all new content and edits.)

**Comment by ktoliver** [comment]
Thanks @aczechowski

**Pull request merged**
