### PR TITLE
Page Update: What is Intune (Overview)

### PR DESCRIPTION
**Pull request by allusai**
I would like to suggest an improvement to the "What is Intune" page.  The original introduction does a good job at introducing Intune, but as a first-time user of Intune I felt that it talked about so many services in one paragraph that can integrate with Intune that I got confused as to what Intune itself is capable of doing. 

That’s why I am submitting this new version which has one dedicated paragraph to talk about situations where Intune can be used and what capabilities Intune provides. Then I made a separate paragraph to talk about how Intune fits in with Microsoft’s other services and integrations that can be made with them. Since Microsoft 365 is probably one of the most popular services that Intune users will be using, I made sure to highlight it with the last sentence of my new version in a way that also shows how useful Intune can be for an organization that uses Microsoft 365. For new Intune customers, I feel like this version will be a lot clearer and show them how Intune can help empower their organization to achieve more!

### CODE REVIEW

**Comment by PRMerger20** [comment]
@allusai : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@MandiOhlinger : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MandiOhlinger** [comment]
@allusai Thank you! And, congrats on your first pull request. These are great additions, and definitely improved this article. We want and encourage community contributions to make our docs better. Keep 'em coming :). 

FYI, I made some text edits to meet our style guidelines. Thanks again!

#sign-off

**Comment by PRMerger13** [comment]
@MandiOhlinger: I'm sorry - only the author of this article, @dougeby, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by allusai** [comment]
Thank you so much Mandi! I really appreciate it! I'm looking forward to making more contributions :)

**Pull request merged**
