### PR TITLE
Update upgrade-on-premises-infrastructure.md

### PR DESCRIPTION
**Pull request by GambitC90**
This should be the SMS Node, not the CCM Node - I worked with a customer having this issue and the CCM Node shouldn't have SMS Admins added to it, but the SMS Node should.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@GambitC90 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by aczechowski** [comment]
LOL, this value is highly contested, it's flipped several times in the past several months
- #1568 
- #2120 

See my comment from 2120 with comment from engineering: https://github.com/MicrosoftDocs/memdocs/pull/2120#pullrequestreview-788643029

So maybe the fix here is to note both with some more explanation.
Thanks @GambitC90 for the contribution, but I'm going to close this request, and I'll take an action later today to revise this bit with some more info.

**Comment by aczechowski** [comment]
Had a side chat with Chris as I looked at this in more detail. I'm actually going to reopen and accept this PR, to help put the article back into the correct state.

Here's the history:

- #1568, issue on 2021-04-28 that suggested both values need to be ccm

  - Private PR where I made the change on 2021-09-09: https://github.com/MicrosoftDocs/memdocs-pr/pull/5425/commits/b4bb69104e51a5a24fe144c5cab4c0736a921338, updated both lines 107 & 113

- #2120, pull request on 2021-10-21 that only fixed line 114

So then this PR is needed to fix line 108.

Thanks @GambitC90 😁

**Comment by aczechowski** [comment]
#label:"ready-to-merge"

**Pull request merged**
