### PR TITLE
Update apps-add-office365.md

### PR DESCRIPTION
**Pull request by Hani-Microsoft**
clarify onedrive ODT support

### CODE REVIEW

**Comment by PRMerger17** [comment]
@Hani-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@Hani-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@Erikre : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Erikre** [comment]
#sign-off

**Pull request merged**
