### PR TITLE
Update enrollment-restrictions-set.md

### PR DESCRIPTION
**Pull request by msbemba**
removed the contradicting note as Windows supports major.minor.build.rev for Windows 10 and Windows 11

Please confirm

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/memdocs/issues/1619

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
