### PR TITLE
Updated co-managment path 2

### PR DESCRIPTION
**Pull request by fabianescacr**
Provided general information about co-managment path 2, this will help customer to understand which path they have to follow depending of their scenario

### CODE REVIEW

**Comment by PRMerger10** [comment]
@fabianescacr : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by PRMerger13** [comment]
@aczechowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
#sign-off

**Pull request merged**
