### PR TITLE
Removing ADAL

### PR DESCRIPTION
**Pull request by rwike77**
ADAL is being deprecated in June: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-migration . Cleaning up content before the deprecation.

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@rwike77 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
#label:"aq-pr-triaged"

**Comment by Brenduns** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
