### PR TITLE
Update Exception Information for D4C

### PR DESCRIPTION
**Pull request by MS-Fraser**
Information related to Defender for Cloud - Defender for Servers functionality being unavailable is incorrect. This dependency is linked to the agent leverage in Defender for Cloud - Defender for Servers (Unified Solution Agent), This is the default option in Defender for Servers P1 and has now been recently added to Defender for Servers P2 (Our original plan) - https://techcommunity.microsoft.com/t5/microsoft-defender-for-cloud/defender-for-servers-plan-2-now-integrates-with-mde-unified/ba-p/3527534

I have updated this exception to mention the SKU of Defender for Cloud and Agent Type which doesn't allowed for this functionality. Please feel free to change but it needs to be correct, I have had two partners reach out to me regarding this.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]
Copy review.

**Comment by Brenduns** [comment]
Pending review, as there is some active cross group review ongoing for this article and the license details.

**Comment by yogkumgit** [comment]
@Brenduns Any update.

**Comment by Brenduns** [comment]
[yogkumgit](https://github.com/yogkumgit)  I've bumped the email thread wiht the Intune and Defender dev teams again, seeking confirmation/validation of the suggested edits.

**Comment by Brenduns** [comment]
I'll be closign this PR without action, as it has been superceeded by https://github.com/MicrosoftDocs/memdocs-pr/pull/8273 which was submitted by a M365 Defender PM, and provides a more direct refinement of the license details.  However this PR remains valued as it helped force the question/clarification that was needed.

**Pull request closed without merging**
