### PR TITLE
Update endpoint-security-edr-profile-settings.md

### PR DESCRIPTION
**Pull request by Dansimp**
removing date metadata to show when it was last updated (per cust feedback)

### CODE REVIEW

**Comment by PRMerger13** [comment]
@Dansimp : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Dansimp** [comment]
#879

**Comment by Dansimp** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@Dansimp: I'm sorry - only the author of this article, @brenduns, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by Brenduns** [comment]
#hold-off

**Pull request closed without merging**
