### PR TITLE
Clarification on silent enablement

### PR DESCRIPTION
**Pull request by pamcdo**
Added a note to say that silent enablement will only encrypt used disk space. This is a frequently asked question around this setting.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@pamcdo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Brenduns** [comment]
Pending review with PM/Engineering.

**Comment by Brenduns** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
