### PR TITLE
Update app-configuration-managed-home-screen-app.md

### PR DESCRIPTION
**Pull request by chmaguir**
made a bunch of additions and some deletions to this doc to have it match the changes we've made to Managed Home Screen.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@chmaguir : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Erikre** [comment]
@sign-off

**Comment by dougeby** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@dougeby: I'm sorry - only the author of this article, @Erikre, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
