### PR TITLE
Update device-enrollment-program-enroll-ios.md

### PR DESCRIPTION
**Pull request by msbemba**
removed authenticate by company portal as it was deprecated in dec 2021 per MC284343

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
issue#https://github.com/MicrosoftDocs/memdocs/issues/2089

**Comment by PRMerger16** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@lenewsad Please review and merge this PR. Thanks

**Comment by yogkumgit** [comment]
@lenewsad Gentle reminder, Please merge this PR. Thanks

**Review by lenewsad — APPROVED** [review]
Thanks @msbemba!

**Comment by lenewsad** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
