### PR TITLE
Update licenses.md

### PR DESCRIPTION
**Pull request by cekunze**
Added Microsoft 365 A1 to list of suites Intune is included

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Erikre Please review and signoff this PR. Thanks

**Comment by yogkumgit** [comment]
@Erikre cc @dougeby Kindly update. Thanks

**Review by Erikre — APPROVED** [review]

**Comment by Erikre** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Comment by Erikre** [comment]
A1 Education is presented here:
https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education

Closing this now.

**Pull request closed without merging**
