### PR TITLE
Update devices-wipe.md

### PR DESCRIPTION
**Pull request by msbemba**
Removed the note as we still get an option to wipe or retire the device even after the user account is removed from Azure AD

per issue#https://github.com/MicrosoftDocs/memdocs/issues/3008

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by PRMerger5** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Smritib17 Please review and Signoff this PR. Thanks

**Review by Smritib17 — APPROVED** [review]

**Comment by Smritib17** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
