### PR TITLE
Update device-inventory.md

### PR DESCRIPTION
**Pull request by msbemba**
Added Windows 11 to the note for the enrolled date

Fixes https://github.com/MicrosoftDocs/memdocs-pr/issues/13031

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Smritib17 Please review and sign off this PR. Thanks

**Comment by yogkumgit** [comment]
@Smritib17 Gentle reminder.

**Comment by Smritib17** [comment]
Closing this PR, pending confirmation from the PM.

**Pull request closed without merging**
