### PR TITLE
Update enroll-your-device-in-intune-macos-cp.md

### PR DESCRIPTION
**Pull request by theneiljohnson**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@theneiljohnson : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by lenewsad — APPROVED** [review]

**Comment by lenewsad** [comment]
Thanks for your contribution @theneiljohnson.

**Comment by lenewsad** [comment]
#sign-off

**Pull request merged**
