### PR TITLE
Update device-profile-monitor.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to check device/user check-in status, device assignment status, and per-configuration status in the configuration profile.

reference - https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new#device-configuration

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by PRMerger3** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/memdocs/issues/2601

**Comment by PRMerger15** [comment]
@MandiOhlinger : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@MandiOhlinger : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by MandiOhlinger — APPROVED** [review]

**Comment by MandiOhlinger** [comment]
#sign-off

**Pull request merged**
