### PR TITLE
Update device-inventory.md

### PR DESCRIPTION
**Pull request by msbemba**
The restart action on this page can be performed on Android,  iOS/iPadOS, and Windows devices. So removed the windows only tag

### CODE REVIEW

**Comment by PRMerger13** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
issue#https://github.com/MicrosoftDocs/memdocs/issues/1844

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@ErikjeMS Please review and merge this PR. Thanks

**Comment by ErikjeMS** [comment]
#sign-off

**Comment by PRMerger20** [comment]
@ErikjeMS: I'm sorry - only the author of this article, @Smritib17, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
