### PR TITLE
Update remote-help.md

### PR DESCRIPTION
**Pull request by ajf8729**
Updated file name in detection rule

### CODE REVIEW

**Comment by PRMerger8** [comment]
@ajf8729 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by Brenduns** [comment]
@ajf8729  Thanks for this PR submission Anthony, we very much appreciate public PR's for edits. 
We can accept the change of case to _Remote help_ for the folder path, but not the change of name for the command line. That must remain _remotehelpinstaller.exe_, as that was a change implemented in the download files for remote help on December 8th.  That was updated in docs, but it wasn’t known this was a change in the download files that we stumbled onto until yesterday, December 9th.  The name change was made to resolve some installation issues.  With details of that change being communicated to me yesterday, we then added a note about this to the live documentations opening section,  which you can view at this time.  https://docs.microsoft.com/mem/intune/remote-actions/remote-help

If you can remove the second edit from your PR for the command line, I’ll accept it, which will give you a contributor’s notation for the article. Otherwise, I’ll need to decline the entire submission as the folder name capitalization isn’t so urgent as to need republication, but the correct installer file name, that aligns to the currently available download, needs to remain intact. 

If you’re seeing something different with a newly downloaded remote help files, let me know those deeper detailis and we can revisit this.

**Comment by ajf8729** [comment]
I had added Remote Help to Intune today and found that it initially failed, due to incorrect detection. I found that the filename mentioned in the docs was incorrect, based on what I am seeing with the most recent installer:

Get-Item -Path 'C:\Program Files\Remote help\RemoteHelp.exe' | select -exp VersionInfo | ft -AutoSize

ProductVersion   FileVersion                                            FileName
--------------   -----------                                            --------
10.0.10011.16384 10.0.10011.16384 (GitEnlistment(jforster).211112-1614) C:\Program Files\Remote help\RemoteHelp.exe

C:\Program Files\Remote help\RemoteHelpInstaller.exe doesn't exist.

**Comment by Brenduns** [comment]
@ajf8729  Thanks for that clarification. I"m going to pass this to our engineering team to ensure they have everything set as expected in the download and as represented by docs.  I'll send and update when I have more to share.

**Comment by Brenduns** [comment]
@ajf8729   Could you confirm the name of the file download you have for remote help? It should be remotehelpinstaller.exe, which was previusly remotehelp.exe.  Before Preceeding, I need to confirm your source file is the correct one. 
image

**Comment by Brenduns** [comment]
@ajf8729  Ah, hang on, and I'm sorry. I misread the edit earlier, and I see it now. Looks like your change submission is spot on, as that's the detection rule for the remote help executable.  I'm going to sign-off on this to get it into the published docs. 

Again, thanks for this submission and for humoring me while I have more coffee this morning and get my head in the game. :) 

#sign-off

**Comment by ajf8729** [comment]
No problem, thanks much! Go get another cup of coffee!

**Pull request merged**
