### PR TITLE
Update enable-tls-1-2-protocol-security-provider.md

### PR DESCRIPTION
**Pull request by jowiswel**
include the full path to the Protocols registry key to make it easier to find for review before going to the linked document

### CODE REVIEW

**Comment by PRMerger10** [comment]
@jowiswel : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by aczechowski — APPROVED** [review]
Thanks @jowiswel for the edit, and thank you for your first contribution to MEMDocs! 🎉

**Comment by aczechowski** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@aczechowski: I'm sorry - only the author of this article, @mestew, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by aczechowski** [comment]
#label:"ready-to-merge"

**Pull request merged**
