### PR TITLE
Added step to add Client Secret to request

### PR DESCRIPTION
**Pull request by dvorachek**
We received a customer ticket in which the customer followed this guide and was unable to authenticate. I was able to replicate this. In order to successfully authenticate I created a client secret within the native app and added that secret as part of the OAuth2 token. I've added these additional steps in this PR.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@dvorachek : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Erikre** [comment]
#sign-off

**Comment by ktoliver** [comment]
@dvorachek Could you take a moment to sign the Contributor License Agreement (CLA)? Then, we can merge the PR.

**Comment by PRMerger13** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @erikre - In line 137, is "Request access token locally" a check box that you select? I don't see the items in that step in the image, so I can't confirm it. Thanks.

**Comment by dvorachek** [comment]
> Hi @Erikre or @dvorachek - In line 137, is "Request access token locally" a check box that you select? I don't see the items in that step in the image, so I can't confirm it. Thanks.

I don't see "Request access token locally" as an option in Postman, so I'm not sure about that, perhaps it's okay to remove.

**Comment by PRMerger16** [comment]
@dvorachek : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Erikre** [comment]
@ktoliver - If I understand correctly, part of the change is to remove "Request access token locally". Maybe I'm misunderstanding, but the PR looks good. Also, dvorachek is Microsoft internal.

**Comment by ktoliver** [comment]
@erikre Thanks; merging now.

**Pull request merged**
