### PR TITLE
Added Note about exclusion merge

### PR DESCRIPTION
**Pull request by Stroell**
Added Note about exclusion merge, so it is clear that the applied exclusions list is a combination from all deployed policies

### CODE REVIEW

**Comment by PRMerger6** [comment]
@Stroell : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@mestew @aczechowski Would one of you be able to review the proposed update? Thanks.

**Comment by ktoliver** [comment]
@mestew for review

Thanks.

**Review by JohanFreelancer9 — CHANGES_REQUESTED** [review]
Copy review. This PR is quite old. I am not sure if it is still relevant.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by dougeby** [comment]
This PR is now 3 years old, but still seems relevant so merging.

**Pull request merged**
