### PR TITLE
Update ios-device-features-settings.md

### PR DESCRIPTION
**Pull request by msbemba**
Corrected  type of alert for notifications for this app

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by PRMerger4** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/memdocs/issues/1944

**Comment by MandiOhlinger** [comment]
@msbemba In this article, the setting names match the UI. In this PR, you changed the setting names, so now they don't match what's in the UI. 

As a result, this PR can't be merged as-is. 

You can update the descriptions:

- A banner is briefly shown with the notification.
- The notification is shown and users must manually dismiss it before continuing to use the device.

**Comment by msbemba** [comment]
Thank you @MandiOhlinger I'll update and close the PR.

**Pull request closed without merging**
