### PR TITLE
Update manage-microsoft-edge.md

### PR DESCRIPTION
**Pull request by msbemba**
Removed blank from om.microsoft.intune.mam.managedbrowser.NetworkStackPref  in the document

fixes https://github.com/MicrosoftDocs/memdocs/issues/4036

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Erikre Please review and sign off this PR. Thanks

**Comment by yogkumgit** [comment]
@Erikre Gentle reminder

**Review by Erikre — APPROVED** [review]

**Comment by Erikre** [comment]
#sign-off

**Review by Erikre — APPROVED** [review]

**Pull request merged**
