### PR TITLE
Update windows-10-feature-updates.md

### PR DESCRIPTION
**Pull request by msbemba**
End User Update Status has been removed, Updated documentation

Fixes https://github.com/MicrosoftDocs/memdocs/issues/3981

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Brenduns Please review and signoff this PR. Thanks

**Comment by Brenduns** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
