### PR TITLE
Update apps-company-portal-macos.md

### PR DESCRIPTION
**Pull request by msbemba**
updated Intune Shell Script Samples - Company Portal.

Fixes#https://github.com/MicrosoftDocs/memdocs/issues/3609

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Comment by tiburd** [comment]
@Erikre 
Please confirm that the URL update is correct and @ mention me in your reply so that I can merge the PR.
Thanks!

**Review by Erikre — APPROVED** [review]

**Comment by Erikre** [comment]
#sign-off

**Pull request merged**
