### PR TITLE
Update device-restrictions-ios.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated built-in apple-apps document 
fixes#https://github.com/MicrosoftDocs/memdocs/issues/3612

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@MandiOhlinger Please merge this PR. Thanks

**Comment by MandiOhlinger** [comment]
@msbemba Please remove the language identifiers in the URLs you updated (en-us). Then, we will merge. Thank you!

**Comment by msbemba** [comment]
Sorry about that. This has been fixed now and ready to merge.

**Review by MandiOhlinger — APPROVED** [review]

**Comment by MandiOhlinger** [comment]
#sign-off

**Pull request merged**
