### PR TITLE
Update android-oem-configuration-overview.md

### PR DESCRIPTION
**Pull request by msft-jy**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@msft-jy : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MandiOhlinger** [comment]
#sign-off

PR mergers - it'd be great if you could update the following text:

**FROM**: OEMs must register their OEMConfig apps with Google to enable these features guarantee correct functioning.

**TO**: OEMs must register their OEMConfig apps with Google. If you don't register, these features may not work as expected.

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@MandiOhlinger Done!

**Pull request merged**
