### PR TITLE
Updated-5120578

### PR DESCRIPTION
**Pull request by Lovina-Saldanha**
Updated for task 5120578.  Linked to Bitlocker Deployment Comparison Chart.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@Lovina-Saldanha : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@Lovina-Saldanha : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Brenduns** [comment]
#sign-off    @Lovina-Saldanha Thanks for those link additions!

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
Hi @Lovina-Saldanha, thanks for adding the link, good stuff. In the future, you can use our private repo, memdocs-pr for additional workflow 😄

**Pull request merged**
