### PR TITLE
Update apps-add-microsoft-365-02.png

### PR DESCRIPTION
**Pull request by msbemba**
Updated the Image with new options

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/memdocs/issues/3118

**Comment by yogkumgit** [comment]
@Erikre Please review and signoff this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by Erikre — APPROVED** [review]

**Comment by Erikre** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this Pr. Thanks

**Pull request merged**
