### PR TITLE
Update on CMG Connection Point

### PR DESCRIPTION
**Pull request by pamcdo**
Previous wording for this section didn't have clear actions for the administrator to execute. I think this update will better enable those reading it to get this piece up and running.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@pamcdo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@aczechowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by aczechowski — APPROVED** [review]
Thanks @pamcdo for the contribution! It's a fair point. We generally try to not duplicate content when possible, but at times it makes sense to do so. Especially in the case of such a popular feature. 😄 

I made some tweaks to the wording for style. For example, we try to avoid talking about "click" or "right-click" as that implies the use of a mouse. We try to be inclusive for all users.

**Comment by aczechowski** [comment]
#sign-off

**Pull request merged**
