### PR TITLE
Fixed a formatting issue on iOS/iPadOS Entollment

### PR DESCRIPTION
**Pull request by brookd2404**
https://docs.microsoft.com/en-us/mem/intune/fundamentals/whats-new#intune-supports-sign-in-from-another-device-during-iosipados-setup-assistant-with-modern-authentication 

Currently missing a bracket to format the link.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@brookd2404 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Erikre Please review and signoff this PR. Thanks

**Review by Erikre — APPROVED** [review]

**Comment by Erikre** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Comment by tiburd** [comment]
@Erikre @Brenduns 
Hi,
Can one of you please fix the file conflict and then @ mention me to merge this PR?
Thank you!

**Comment by Brenduns** [comment]
@tiburd  Conflict resolved. Good to go!
cc @Erikre

**Pull request merged**
