### PR TITLE
Updated RelationType enum in SMS_AppRelation_Flat to reflect enum from CM 2006

### PR DESCRIPTION
**Pull request by TheToor**
Enum extracted from v_CIRelationTypes on CM Version 2006.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@TheToor : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@aczechowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by aczechowski — APPROVED** [review]
Thanks @TheToor for the contribution! I confirmed the list, and found value 25 for app groups as well, which I added.

**Comment by aczechowski** [comment]
#sign-off

**Pull request merged**
