### PR TITLE
Update settings.md

### PR DESCRIPTION
**Pull request by iceorbital**
rearranging to match Intune UI

### CODE REVIEW

**Comment by PRMerger14** [comment]
@iceorbital : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by iceorbital** [comment]
@mestew i created this on the public docs, sorry!

**Review by mestew — APPROVED** [review]

**Comment by mestew** [comment]
#sign-off

**Comment by ktoliver** [comment]
Hi @iceorbital @mestew - The "Next steps" heading in this article doesn't have any content: (live site) https://docs.microsoft.com/en-us/mem/analytics/settings#next-steps

Could I remove the heading or add a relevant link before merging?  Thanks.

**Comment by ktoliver** [comment]
I'll go ahead and merge this update. A follow-up can be done separately. Thanks.

**Pull request merged**
