### PR TITLE
Update Screenshot for Microsoft Store for Business

### PR DESCRIPTION
**Pull request by Yogesh-Shede**
Hi, I haven't seen any screenshot for Microsoft Store for Business on this link. I think this will be helpful to everyone.
Please add screenshot if this fine from your end.

Link > https://docs.microsoft.com/en-us/mem/intune/apps/windows-store-for-business#associate-your-microsoft-store-for-business-account-with-intune

### CODE REVIEW

**Comment by PRMerger14** [comment]
@Yogesh-Shede : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @Yogesh-Shede. 

Thanks for contributing to the documentation. 

It's not possible to submit image files through the GitHub UI, but you can complete the [tool setup steps](https://docs.microsoft.com/contribute/get-started-setup-tools) that are detailed in the Microsoft Docs contributor guide and submit image files in a pull request that way. 

Thanks!

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by ktoliver** [comment]
@Erikre for review

Thanks.

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Erikre cc @dougeby Kindly update. Thanks

**Comment by Erikre** [comment]
Although the added image looks good, it is saved in public location and MSfB is being deprecated. Closing this PR because the update is no longer necessary. Thanks

**Pull request closed without merging**
