### PR TITLE
Update apps-win32-add.md

### PR DESCRIPTION
**Pull request by 38cat**
Win32 apps can installing on Azure AD Registered device.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@38cat : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@38cat : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by 38cat** [comment]
Hi @Erikre,
I added line 115, below.
"When device is  enrolled by Azure AD registered,  you need to select **System**."

If Azure AD Registered device, I think required system context.
Please, confirm.

**Comment by PRMerger6** [comment]
@38cat : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Erikre — APPROVED** [review]

**Comment by Erikre** [comment]
@38cat - Looks good. Thanks for the contribution. #sign-off

**Comment by PRMerger20** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
