### PR TITLE
Update defender-advanced-threat-protection.md

### PR DESCRIPTION
**Pull request by gowdhamankarthikeyan**

### CODE REVIEW

**Comment by gowdhamankarthikeyan** [comment]
#sign-off

**Review by BalaDelli — APPROVED** [review]

**Comment by BalaDelli** [comment]
#sign-off

**Comment by gowdhamankarthikeyan** [comment]
#sign-off

**Comment by dougeby** [comment]
This was signed-off on but not merged. Merging.

**Pull request merged**
