### PR TITLE
CA policy update

### PR DESCRIPTION
**Pull request by anbiswas-microsoft**
CA Policy update 9/22

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@anbiswas-microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ErikjeMS** [comment]
@anbiswas All ID entries need to an associated ADO item, along with approval from Tracey. What's the ADO # for this one?
#hold-off

**Comment by anbiswas-microsoft** [comment]
+ @Tracey ***@***.***>

This is the ADO Item for reference: Scenario 34931544: [PM Only] Group AVD and Windows 365 apps to configure the correct Conditional Access experience - Boards (visualstudio.com)<https://microsoft.visualstudio.com/OS/_workitems/edit/34931544>

Best,
--
Ankur Biswas
Program Manager
Windows 365
Office: +1 (425) 7228048
***@***.******@***.***>
[Microsoft]
﻿ One Microsoft Way, Redmond, WA 98052 USA

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by ErikjeMS** [comment]
@anbiswas-microsoft Let's work on this in the ADO item 36360788 and then use the -pr repo to create a PR. This public repo isn't where we handle In Development items.

**Comment by anbiswas-microsoft** [comment]
Thanks Ankur! @Erik ***@***.***> this is the release readiness task item associated. Task 36360788: RR Triage: [PM Only] Group AVD and Windows 365 apps to configure the correct Conditional Access experience (visualstudio.com)<https://microsoft.visualstudio.com/OS/_queries/edit/36360788/?triage=true>

ID blurb is in draft.

From: Ankur Biswas ***@***.***>
Sent: Thursday, September 23, 2021 9:46 PM
To: MicrosoftDocs/memdocs ***@***.***>; MicrosoftDocs/memdocs ***@***.***>; Tracey Adams ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [MicrosoftDocs/memdocs] CA policy update (#2011)

+ @Tracey ***@***.***>

This is the ADO Item for reference: Scenario 34931544: [PM Only] Group AVD and Windows 365 apps to configure the correct Conditional Access experience - Boards (visualstudio.com)<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.visualstudio.com%2FOS%2F_workitems%2Fedit%2F34931544&data=04%7C01%7Ctraceyadams%40microsoft.com%7Cf3f749f7fa704f023c2e08d97f1624ae%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637680555358984194%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gk5HvtOTBDSSO2Y%2B5JyXF8d7537CCAw0cXrb6Cz7Iag%3D&reserved=0>

Best,
--
Ankur Biswas
Program Manager
Windows 365
Office: +1 (425) 7228048
***@***.******@***.***>
[Microsoft]
﻿ One Microsoft Way, Redmond, WA 98052 USA

**Pull request closed without merging**
