### PR TITLE
Update remove-certificates.md

### PR DESCRIPTION
**Pull request by msbemba**
The certificate is removed from the client but it doesn't get revoked. It does get revoked if I use the "wipe" feature on the device.

Made changes accordingly

Fixes https://github.com/MicrosoftDocs/memdocs/issues/4118

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Brenduns Please review and signoff this PR. Thanks

**Comment by Brenduns** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Comment by tiburd** [comment]
#sign-off

**Comment by traya1** [comment]
#sign-off

**Comment by tiburd** [comment]
@Brenduns 
THANK YOU for merging!

**Pull request merged**
