### PR TITLE
Update _SMSTSMediaType

### PR DESCRIPTION
**Pull request by ChadSimmons**
Define the variable values for each of the known _SMSTSMediaType options

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@ChadSimmons : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by aczechowski — APPROVED** [review]
Thanks @ChadSimmons for the contribution!

**Comment by aczechowski** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
