### PR TITLE
Update configuration-manager-on-azure.yml

### PR DESCRIPTION
**Pull request by baardhermansen**
Changed an "on" to an "or".

### CODE REVIEW

**Comment by PRMerger5** [comment]
@baardhermansen : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by aczechowski — APPROVED** [review]
Thanks @baardhermansen, good catch! 😄 🎉

**Comment by aczechowski** [comment]
#sign-off

**Comment by baardhermansen** [comment]
> Thanks @baardhermansen, good catch! 😄 🎉

I aim to please :P

**Pull request merged**
