### PR TITLE
Update task-sequence-steps.md

### PR DESCRIPTION
**Pull request by gwblok**
Added info about DisableCMDRequest.TAG

### CODE REVIEW

**Comment by PRMerger13** [comment]
@gwblok : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @gwblok for the contribution, I'm checking with the engineering team.

**Comment by aczechowski** [comment]
Hi @gwblok, I'm unfortunately going to decline this contribution. It's a level of detail and technically a "hack" that we don't want to officially document (thus support). As I mentioned in #768, the best thing would be to file a UserVoice idea to describe the scenario, and suggest a new product feature to control the behavior in a supported way.

**Comment by gwblok** [comment]
Thanks Aaron, thanks for letting me know.  Totally understand.

**Pull request closed without merging**
