### PR TITLE
Update device-compliance-partners.md

### PR DESCRIPTION
**Pull request by msbemba**
Added  Addigy's documentation at the bottom of the page in the next steps section

Fixes https://github.com/MicrosoftDocs/memdocs/issues/4296

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@lenewsad Please review and sign off this PR. Thanks

**Comment by lenewsad** [comment]
#sign-off

**Review by lenewsad — APPROVED** [review]

**Comment by yogkumgit** [comment]
Please merge this PR. Thanks

**Pull request merged**
