### PR TITLE
Update ios-ipados-app-configuration-policies.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the document with links to both Add iOS store apps to Microsoft Intune and Add app configuration policies for managed iOS/iPadOS devices

fixes#https://github.com/MicrosoftDocs/memdocs/issues/3418

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by traya1** [comment]
Learn Build status updates of commit _[d268dbd](https://github.com/msbemba/memdocs/commits/d268dbdf60d18371258d217170016bf9cabaa83a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[memdocs/intune/enrollment/ios-ipados-app-configuration-policies.md](https://github.com/msbemba/memdocs/blob/patch-182/memdocs/intune/enrollment/ios-ipados-app-configuration-policies.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/aa268e4d-aaaf-30c8-4118-35d62ca794c9/202212140654323138-3454/BuildReport?accessString=a58cc8b069da7f215d7003fda407e433db349edf02e9c750fe7fceae40fbcf1c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/aa268e4d-aaaf-30c8-4118-35d62ca794c9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@lenewsad Please review and signoff this PR. Thanks

**Review by lenewsad — APPROVED** [review]

**Comment by lenewsad** [comment]
#sign-off

**Comment by traya1** [comment]
Learn Build status updates of commit _[d55634b](https://github.com/msbemba/memdocs/commits/d55634b5aaad1f16209043d6579d1323272d8db2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[memdocs/intune/enrollment/ios-ipados-app-configuration-policies.md](https://github.com/msbemba/memdocs/blob/patch-182/memdocs/intune/enrollment/ios-ipados-app-configuration-policies.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/aa268e4d-aaaf-30c8-4118-35d62ca794c9/202212141733191741-3454/BuildReport?accessString=d5853139d97a52544d783d45e0e83f49a9bd7f3b495aded5204b86c28d175eea).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/aa268e4d-aaaf-30c8-4118-35d62ca794c9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
