### PR TITLE
Update advanced-threat-protection-configure.md

### PR DESCRIPTION
**Pull request by mjcaparas**
Update to use Endpoint detection and response under **Endpoint security > Endpoint detection and response** rather than Devices > Configuration profiles.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@mjcaparas : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Brenduns** [comment]
@mjcaparas  Thanks for this PR. I don't see the new image you reference in the edits. . :( Did it get added?

**Comment by PRMerger6** [comment]
@Brenduns : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Brenduns** [comment]
Waiting to sign-off on this until a separate PR that adds an image to master is merged to master.  That new image is referenced in this PR.

**Comment by Brenduns** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
I've verified that the image referenced in the article in this PR is in master at the referenced path.

**Pull request merged**
