### PR TITLE
Changed 'scheduler.log' to 'schedule.log' in image.

### LINKED ISSUE #1180: The log file is schedule.log, not scheduler.log (Prepare the install job)
The flowchart refers to a wrong log file in "Prepare the install job" phase. The correct log file name is schedule.log, not scheduler.log.

Panu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4466280-5fdf-18e9-7d15-ce6259ec641b
* Version Independent ID: ea742435-b7e9-de0b-647e-a31881b8e34c
* Content: [Set up site server in passive mode - Configuration Manager](https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/passive-site-server-flowchart)
* Content Source: [memdocs/configmgr/core/servers/deploy/configure/passive-site-server-flowchart.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/configmgr/core/servers/deploy/configure/passive-site-server-flowchart.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

### PR DESCRIPTION
**Pull request by ChrisKibble**
Fixes #1180 

I did not validate the log file, I took @aczechowski's comment that the original issue was accurate and the log file name needed to be changed.

### CODE REVIEW

**Review by aczechowski — APPROVED** [review]
Thanks @ChrisKibble for making the change. I updated my source Visio too 😄

**Comment by aczechowski** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@aczechowski: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by aczechowski** [comment]
@ktoliver thanks for assigning this to me, assuming based on the issue filed for the article on which I'm the author. I guess PRMerger can't handle an image that doesn't have an author metatag.

**Comment by ktoliver** [comment]
> @ktoliver Kristine Toliver (Aquent LLC) Vendor thanks for assigning this to me, assuming based on the issue filed for the article on which I'm the author. I guess PRMerger can't handle an image that doesn't have an author metatag.

@aczechowski Yes, that's exactly correct. Thanks for the review; we'll merge now.

**Pull request merged**
