### PR TITLE
Update create-dynamic-device-group-all-cloudpcs.md

### PR DESCRIPTION
**Pull request by chadhamilton37**
Changed the value in step 3 of Item 6 to "Cloud PC" instead of "CloudPC". "CloudPC" doesn't produce the desired result for the dynamic group.

### CODE REVIEW

**Comment by PRMerger4** [comment]
@chadhamilton37 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@erikjeMS Could you take a look? Note that this was recently changed in the reverse, in https://github.com/MicrosoftDocs/memdocs/pull/1953. 

Thanks.

**Comment by ErikjeMS** [comment]
@ktoliver Yes, I checked with PM. It should be spaced.

**Comment by ktoliver** [comment]
> Yes, I checked with PM. It should be spaced.

@ErikjeMS Thanks; we'll merge the update.

**Pull request merged**
