### PR TITLE
Update defender-advanced-threat-protection.md

### PR DESCRIPTION
**Pull request by pahuijbr**
Added a note to clarify to customers where they can find more information about onboarding the preview version of the new MDE agent for WS2012R2 & 2016.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@pahuijbr : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
#label:"aq-pr-triaged"

**Comment by PRMerger15** [comment]
@aczechowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by aczechowski — APPROVED** [review]
Thanks @pahuijbr for the contribution! I made a few editorial tweaks for style.

I also removed the sentence about future capabilities, that's something we generally avoid in official product docs. For your reference, here's the link to the _internal_ contributor guide that explains it further: [What can I publish on docs.microsoft.com](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-channel-guidance?branch=master#unauthorized-content) (scroll down to the bullet for "future product plans").

Also, as a Microsoft employee, I encourage you to use the _private_ repo for your contributions. For more info, see [Workflow for editing a private repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-edit-article-private?branch=master#workflow-for-editing-a-private-repo). 😄

**Comment by aczechowski** [comment]
#label:"ready-to-merge"

**Comment by pahuijbr** [comment]
Thanks for the review Aaron – fyi I tried to use the private repo method (have been doing this, successfully, a lot for Defender docs) but it gave me a 404.

**Pull request merged**
