### PR TITLE
Update troubleshoot-microsoft-connected-cache.md

### PR DESCRIPTION
**Pull request by jonasatgit**

### CODE REVIEW

**Comment by PRMerger7** [comment]
@jonasatgit : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by aczechowski — APPROVED** [review]
Thanks @jonasatgit for the contribution! 😄

**Comment by aczechowski** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
