### PR TITLE
Update device-restart.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to line 49 as it should only be Android Enterprise personally-owned work profile devices 

Fixes https://github.com/MicrosoftDocs/memdocs/issues/4163

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Smritib17 Please review and sign off this PR. Thanks

**Review by Smritib17 — APPROVED** [review]

**Comment by Smritib17** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
