### PR TITLE
Update quickstart-setup-auto-enrollment.md

### PR DESCRIPTION
**Pull request by quietlikeninja**
Intune Administrator doesn't have the permissions to enabled auto enrollment.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@quietlikeninja : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ErikjeMS** [comment]
Investigating with PM...

**Comment by quietlikeninja** [comment]
Any chance this could just get changed and then changed back if/when the PM confirms its resolved?  Having this incorrect information in place cost me half a day of testing time and made me look unprofessional.  Prior to attending a client site I provided detail of the access I required.  Using the principle of least access I just requested Intune Administrator based off the information on this page. When I didn't have the permissions I then needed to wait for a Global Administrator to be available, and willing, to make the required change.

The same issue has been raised for another page on 13 Nov 2020 - #1002.  While the resolution of that issue may not have resolved the issue on this page it shows that there seems to have been no feedback from the PM for about 3.5 months.

**Comment by ErikjeMS** [comment]
Repinging PM...

**Comment by ErikjeMS** [comment]
@quietlikeninja The PM confirmed that Intune Admin only has read permissions here. Approving this PR: 
#sign-off

**Pull request merged**
