### PR TITLE
Update settings-catalog.md

### PR DESCRIPTION
**Pull request by MikeDano**
update based on a customer question via mail.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@MikeDano : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by MandiOhlinger — APPROVED** [review]

**Comment by PRMerger7** [comment]
@MandiOhlinger : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MandiOhlinger** [comment]
#sign-off

**Comment by MandiOhlinger** [comment]
Merging PR since it was signed off 6 days ago, and still not merged.

**Pull request merged**
