### PR TITLE
Update tutorial-use-device-enrollment-program-enroll-ios.md

### PR DESCRIPTION
**Pull request by Leicham**
added a note to enrollment profiles to highlight enrollment restrictions could block automated enrollment, regardless of user attestation if the platform is blocked

### CODE REVIEW

**Comment by PRMerger10** [comment]
@Leicham : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ErikjeMS** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
I'll fix a typo that was merged in #1754 in a follow-up PR.

**Pull request merged**
