### PR TITLE
Update deploy-management-agent.md

### PR DESCRIPTION
**Pull request by GenerAhl**
It's confusing if switching encryption management authorities requires a re-encryption or not. I have put some more text around the two scenarios and turned into a Note!.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@GenerAhl : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by aczechowski — APPROVED** [review]
Thanks @GenerAhl for the contribution, looks good!

**Comment by aczechowski** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
