### PR TITLE
disabled instead of disable. (IcM below)

### PR DESCRIPTION
**Pull request by Base51**
IcM: 178562033

### CODE REVIEW

**Comment by PRMerger16** [comment]
@Base51 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Erikre** [comment]
I'm verifying this change.

**Comment by Erikre** [comment]
@Base51 - Thanks for the feedback and update. I am having this change published now.

**Comment by Erikre** [comment]
#sign-off

**Pull request merged**
