### PR TITLE
Updated ios app protection policy settings

### PR DESCRIPTION
**Pull request by abasore**
Added clarification for the Local Storage option for iOS 'Save copies of org data' policy.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@abasore : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by abasore** [comment]
@Erikre Is there anything I change for this to be checked in?

**Comment by Erikre** [comment]
#sign-off

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
