### PR TITLE
Update compliance-policy-create-windows.md

### PR DESCRIPTION
**Pull request by matt-call**
Removing confusing conflicting language.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@matt-call : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @matt-call -- This pull request was opened in the public repo. PMs should work in the private repo, per the Microsoft Docs contributor guide. We'll keep this PR open for review and merge, but in the future, would you make content updates in the private repo? Thanks!

**Comment by matt-call** [comment]
I’m aware – was a victim of selecting the wrong branch (since they both show in Github 😊)

--

Matt Call
Senior Program Manager | EMX Customer Acceleration Team | Office: +1 (518) 292-1126 | mattcall@microsoft.com<mailto:mattcall@microsoft.com>
[Microsoft]
﻿ One Microsoft Way, Redmond, WA 98052 USA

Book some time with me<https://book.ms/mattcall@microsoft.com>

**Comment by Brenduns** [comment]
#sign-off

**Pull request merged**
