### PR TITLE
Update enroll-your-device-in-intune-macos-cp.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated OS version, Please check with PM once as this could be a bug as well 

Fixes https://github.com/MicrosoftDocs/memdocs/issues/3734

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Comment by lenewsad** [comment]
> Updated OS version, Please check with PM once as this could be a bug as well
> 
> Fixes #3734

Thanks @msbemba, confirmed with PM!

**Review by lenewsad — APPROVED** [review]

**Comment by lenewsad** [comment]
#sign-off

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR, Thanks

**Pull request merged**
