### PR TITLE
Update compliance-policy-create-android-for-work.md

### PR DESCRIPTION
**Pull request by msbemba**
made changes to the important note to reflect that Android compliance policies should only be targeted at groups of devices

Fixes https://github.com/MicrosoftDocs/memdocs/issues/4415

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@lenewsad Please review and sign off this PR. Thanks

**Comment by lenewsad** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
