### PR TITLE
The people have spoken

### PR DESCRIPTION
**Pull request by AdamGrossTX**
ALL CAPS!! @RobYork is wrong. 

https://twitter.com/configmgrdogs/status/1316490483514793990?s=21

### CODE REVIEW

**Comment by PRMerger10** [comment]
@AdamGrossTX : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by aczechowski — APPROVED** [review]
🤣 Thanks @AdamGrossTX. I'll change the other several instances later today so we're internally consistent.

**Comment by aczechowski** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@aczechowski: I'm sorry - only the author of this article, @mestew, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by mestew** [comment]
#sign-off

**Pull request merged**
