### PR TITLE
Update account-sign-up.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the link for intune to https://endpoint.microsoft.com

### CODE REVIEW

**Comment by msbemba** [comment]
issue#https://github.com/MicrosoftDocs/memdocs/issues/2232

**Comment by PRMerger-2** [comment]
@msbemba : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by yogkumgit** [comment]
@Smritib17 Please merge this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Smritib17 Please review and merge this PR. Thanks

**Review by Smritib17 — APPROVED** [review]

**Pull request merged**
