### PR TITLE
Client Notification Collect Client Logs tip

### PR DESCRIPTION
**Pull request by ChadSimmons**
Add tip to explain collected client log storage location and deletion maintenance schedule

### CODE REVIEW

**Comment by PRMerger9** [comment]
@ChadSimmons : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
Thanks @ChadSimmons for the contribution! I just want to verify with the engineering team.

**Comment by PRMerger20** [comment]
@ChadSimmons : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@aczechowski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aczechowski** [comment]
#sign-off

**Pull request merged**
