### PR TITLE
Update store-apps-company-portal-autopilot.md

### PR DESCRIPTION
**Pull request by Leicham**
Confirmed Issue #1785, this doesn't necessarily apply to Autopilot devices, but any Intune managed device.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@Leicham : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@Leicham : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@Erikre for review

Thanks.

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Comment by yogkumgit** [comment]
@Erikre Please review and merge this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Erikre

**Review by Erikre — APPROVED** [review]

**Comment by Erikre** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Comment by PRMerger14** [comment]
@tiburd : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
