### PR TITLE
Update samsung-knox-apps-allow-block.md

### PR DESCRIPTION
**Pull request by Othou**

### CODE REVIEW

**Comment by PRMerger6** [comment]
@Othou : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MandiOhlinger** [comment]
@Othou Thank you! Why do you think it should be "block" instead of "allow"? Just trying to understand. Did your testing prove this? Any additional information would be great.

**Comment by Othou** [comment]
Hey @MandiOhlinger! I have not tested this, but I would assume it should say block because it is example config for: "For a list of apps that are blocked from running on the device", as row 52 says.
Also on row 56 "..PreventStartPackages..", it indicates that it is blocking an application package.
That's why I think row 58 should say block, since we are doing "a list of apps that are blocked"

**Review by MandiOhlinger — APPROVED** [review]

**Comment by MandiOhlinger** [comment]
@Othou You are correct. Thank you! #sign-off

**Pull request merged**
