### PR TITLE
Update cloud-pc-size-recommendations.md

### PR DESCRIPTION
**Pull request by christiaanbrinkhoff**
Note to endpoint requirements for endpoints. One feedback item from the field.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@christiaanbrinkhoff : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @christiaanbrinkhoff - This pull request was opened in the public repo. PMs should work in the private repo, per the Microsoft Docs contributor guide. We can keep this PR open for review and merge, but would you make future content updates in the private repo? Thank you!

**Comment by PRMerger12** [comment]
@ErikjeMS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ErikjeMS** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@ErikjeMS It looks like the new file you use in the link in line 37 (I revised to fix transposed letters) isn't in master in the public repo yet, so I see a 404 error when I click through. It looks like a sync issue that will resolve when the repositories are synced. I don't know when that will be; possibly not until Tuesday. Is it OK to merge given this information, or do you want to wait to merge until the new file is in master in the public repo?

**Comment by ErikjeMS** [comment]
@ktoliver The new file is in public live right now. So it's okay to merge. Thanks!

**Pull request merged**
