### PR TITLE
Update run-discovery.md

### PR DESCRIPTION
**Pull request by GenerAhl**
Added the two different AAD discovery methods available.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@GenerAhl : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by GenerAhl** [comment]
Ready for review @aczechowski  @mestew

**Review by aczechowski — APPROVED** [review]
Thanks @GenerAhl for making the edit yourself! 😄 🎉 Looks great
Fixes #1994

**Comment by aczechowski** [comment]
#sign-off on behalf of @mestew

**Comment by PRMerger12** [comment]
@aczechowski: I'm sorry - only the author of this article, @mestew, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
