### PR TITLE
Updated device delete action

### PR DESCRIPTION
**Pull request by abasore**
This is a quick change to update the expected behavior for the delete action.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@abasore : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger5** [comment]
@abasore : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger4** [comment]
@abasore : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Smritib17** [comment]
#sign-off

**Pull request merged**
