### PR TITLE
Update windows-update-for-business-configure.md

### PR DESCRIPTION
**Pull request by pelarsen**
Clarify that "Windows Holographic for Business" and other OS is not supported

### CODE REVIEW

**Comment by PRMerger6** [comment]
@pelarsen : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @pelarsen - This pull request was opened in the public repo. PMs should work in the private repo, per the Microsoft Docs contributor guide. We can keep this PR open for review and merge, but would you make future content updates in the private repo? Thank you!

**Comment by PRMerger20** [comment]
@Brenduns : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Brenduns** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
