### PR TITLE
Update device-enrollment-restrictions.md

### PR DESCRIPTION
**Pull request by rafalfitt**
sync with the rest of the doc and with https://github.com/MicrosoftDocs/memdocs/commit/a490e7feefd03339e12d33810696ab021baa8a22

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@lenewsad Please signoff this PR. Thanks

**Review by lenewsad — APPROVED** [review]

**Comment by lenewsad** [comment]
#sign-off

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks.

**Pull request merged**
