### PR TITLE
Update line 116 in device-inventory.md

### PR DESCRIPTION
**Pull request by aendrawos**
Line 116: Supervised Mode is only available for IOS/iPadOS devices

### CODE REVIEW

**Comment by PRMerger19** [comment]
@aendrawos : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by ErikjeMS** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
