### PR TITLE
Apps workload doesn't be set to Intune/Pilot Intune for PowerShell sc…

### PR DESCRIPTION
**Pull request by PanuSaukko**
…ripts

Intune Management Extension will be installed to co-managed devices if you assign PowerShell scripts to co-managed devices and the Apps workload is set to "Configuration Manager".

### CODE REVIEW

**Comment by PRMerger14** [comment]
@PanuSaukko : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@Erikre - can you take a look?

**Comment by Erikre** [comment]
@PanuSaukko - Thanks for the feedback. I worked with the product team to add additional clarity.

**Comment by Erikre** [comment]
#sign-off

**Pull request merged**
